/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CaptableCaptableCompanyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptableCaptableCompanyUpdate{}

// CaptableCaptableCompanyUpdate struct for CaptableCaptableCompanyUpdate
type CaptableCaptableCompanyUpdate struct {
	IncorporationCountry interface{} `json:"incorporationCountry,omitempty"`
	IncorporationState   interface{} `json:"incorporationState,omitempty"`
	IncorporationType    interface{} `json:"incorporationType,omitempty"`
	Name                 interface{} `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CaptableCaptableCompanyUpdate CaptableCaptableCompanyUpdate

// NewCaptableCaptableCompanyUpdate instantiates a new CaptableCaptableCompanyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptableCaptableCompanyUpdate() *CaptableCaptableCompanyUpdate {
	this := CaptableCaptableCompanyUpdate{}
	return &this
}

// NewCaptableCaptableCompanyUpdateWithDefaults instantiates a new CaptableCaptableCompanyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptableCaptableCompanyUpdateWithDefaults() *CaptableCaptableCompanyUpdate {
	this := CaptableCaptableCompanyUpdate{}
	return &this
}

// GetIncorporationCountry returns the IncorporationCountry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableCaptableCompanyUpdate) GetIncorporationCountry() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.IncorporationCountry
}

// GetIncorporationCountryOk returns a tuple with the IncorporationCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableCaptableCompanyUpdate) GetIncorporationCountryOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IncorporationCountry) {
		return nil, false
	}
	return &o.IncorporationCountry, true
}

// HasIncorporationCountry returns a boolean if a field has been set.
func (o *CaptableCaptableCompanyUpdate) HasIncorporationCountry() bool {
	if o != nil && !IsNil(o.IncorporationCountry) {
		return true
	}

	return false
}

// SetIncorporationCountry gets a reference to the given interface{} and assigns it to the IncorporationCountry field.
func (o *CaptableCaptableCompanyUpdate) SetIncorporationCountry(v interface{}) {
	o.IncorporationCountry = v
}

// GetIncorporationState returns the IncorporationState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableCaptableCompanyUpdate) GetIncorporationState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.IncorporationState
}

// GetIncorporationStateOk returns a tuple with the IncorporationState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableCaptableCompanyUpdate) GetIncorporationStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IncorporationState) {
		return nil, false
	}
	return &o.IncorporationState, true
}

// HasIncorporationState returns a boolean if a field has been set.
func (o *CaptableCaptableCompanyUpdate) HasIncorporationState() bool {
	if o != nil && !IsNil(o.IncorporationState) {
		return true
	}

	return false
}

// SetIncorporationState gets a reference to the given interface{} and assigns it to the IncorporationState field.
func (o *CaptableCaptableCompanyUpdate) SetIncorporationState(v interface{}) {
	o.IncorporationState = v
}

// GetIncorporationType returns the IncorporationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableCaptableCompanyUpdate) GetIncorporationType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.IncorporationType
}

// GetIncorporationTypeOk returns a tuple with the IncorporationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableCaptableCompanyUpdate) GetIncorporationTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IncorporationType) {
		return nil, false
	}
	return &o.IncorporationType, true
}

// HasIncorporationType returns a boolean if a field has been set.
func (o *CaptableCaptableCompanyUpdate) HasIncorporationType() bool {
	if o != nil && !IsNil(o.IncorporationType) {
		return true
	}

	return false
}

// SetIncorporationType gets a reference to the given interface{} and assigns it to the IncorporationType field.
func (o *CaptableCaptableCompanyUpdate) SetIncorporationType(v interface{}) {
	o.IncorporationType = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptableCaptableCompanyUpdate) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptableCaptableCompanyUpdate) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CaptableCaptableCompanyUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given interface{} and assigns it to the Name field.
func (o *CaptableCaptableCompanyUpdate) SetName(v interface{}) {
	o.Name = v
}

func (o CaptableCaptableCompanyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptableCaptableCompanyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IncorporationCountry != nil {
		toSerialize["incorporationCountry"] = o.IncorporationCountry
	}
	if o.IncorporationState != nil {
		toSerialize["incorporationState"] = o.IncorporationState
	}
	if o.IncorporationType != nil {
		toSerialize["incorporationType"] = o.IncorporationType
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CaptableCaptableCompanyUpdate) UnmarshalJSON(data []byte) (err error) {
	varCaptableCaptableCompanyUpdate := _CaptableCaptableCompanyUpdate{}

	err = json.Unmarshal(data, &varCaptableCaptableCompanyUpdate)

	if err != nil {
		return err
	}

	*o = CaptableCaptableCompanyUpdate(varCaptableCaptableCompanyUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "incorporationCountry")
		delete(additionalProperties, "incorporationState")
		delete(additionalProperties, "incorporationType")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCaptableCaptableCompanyUpdate struct {
	value *CaptableCaptableCompanyUpdate
	isSet bool
}

func (v NullableCaptableCaptableCompanyUpdate) Get() *CaptableCaptableCompanyUpdate {
	return v.value
}

func (v *NullableCaptableCaptableCompanyUpdate) Set(val *CaptableCaptableCompanyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptableCaptableCompanyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptableCaptableCompanyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptableCaptableCompanyUpdate(val *CaptableCaptableCompanyUpdate) *NullableCaptableCaptableCompanyUpdate {
	return &NullableCaptableCaptableCompanyUpdate{value: val, isSet: true}
}

func (v NullableCaptableCaptableCompanyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptableCaptableCompanyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
