/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TeamTeamRoom type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamTeamRoom{}

// TeamTeamRoom struct for TeamTeamRoom
type TeamTeamRoom struct {
	// Archived reports that the room has been closed. It is the platform's own Space attribute — the same one the Team client writes — and NOT a field of the work facet, so there is exactly one answer to \"is this room open\".
	Archived *bool `json:"archived,omitempty"`
	// Bindings are what this room is ABOUT, each a \"<kind>:<ref>\" string — \"project:acme/web\", \"repo:hanzoai/cloud\", \"issue:1010\". One list rather than one field per kind, because the next thing a room can be about should not be a schema change; and a bound value is opaque here on purpose, since the app that owns a project is the app that can resolve one. HIP-0523 §2: a binding is a REFERENCE, never a copy — a room holding an issue's title or status would be the parallel work-item store HIP-1160 §1 forbids.
	Bindings []string `json:"bindings,omitempty"`
	// Direct reports that this is a room between people rather than a named room. It is derived from the document's class, so it cannot disagree with what the client will render.
	Direct *bool `json:"direct,omitempty"`
	// ID is the room document's own id, and the value the bind op addresses. It is unique within a space, not across the org.
	Id *string `json:"id,omitempty"`
	// Kind is what sort of room this is: \"channel\" (open to everyone in the space), \"private\" (open to its members) or \"dm\" (a conversation between the people in it). It is derived from the class and the private flag, so it cannot disagree with Direct and Private beside it.
	Kind *string `json:"kind,omitempty"`
	// Life is the room's lifecycle INTENT — \"standing\" or \"bound\" (HIP-0523 §2). Absent on the document it reads \"standing\": a room nobody classified is one that persists.
	Life *string `json:"life,omitempty"`
	// Members are the account uuids in the room, agents included: an agent projects as a space member under a uuid derived from its id, so a caller comparing this against GET /v1/bot/members learns which rooms an agent is in.
	Members []string `json:"members,omitempty"`
	// Name is what a person sees in a sidebar. A direct message carries none, so this is empty for one — the members are its name.
	Name *string `json:"name,omitempty"`
	// Private reports that the room is restricted to its members.
	Private *bool `json:"private,omitempty"`
	// Space is the space uuid holding this room. It is part of the room's address: two spaces of one org may each hold a room with the same name, and only the pair identifies one.
	Space *string `json:"space,omitempty"`
	// Topic is the room's own one-line subject, as the Team client sets it.
	Topic                *string `json:"topic,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TeamTeamRoom TeamTeamRoom

// NewTeamTeamRoom instantiates a new TeamTeamRoom object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamTeamRoom() *TeamTeamRoom {
	this := TeamTeamRoom{}
	return &this
}

// NewTeamTeamRoomWithDefaults instantiates a new TeamTeamRoom object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamTeamRoomWithDefaults() *TeamTeamRoom {
	this := TeamTeamRoom{}
	return &this
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *TeamTeamRoom) SetArchived(v bool) {
	o.Archived = &v
}

// GetBindings returns the Bindings field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetBindings() []string {
	if o == nil || IsNil(o.Bindings) {
		var ret []string
		return ret
	}
	return o.Bindings
}

// GetBindingsOk returns a tuple with the Bindings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetBindingsOk() ([]string, bool) {
	if o == nil || IsNil(o.Bindings) {
		return nil, false
	}
	return o.Bindings, true
}

// HasBindings returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasBindings() bool {
	if o != nil && !IsNil(o.Bindings) {
		return true
	}

	return false
}

// SetBindings gets a reference to the given []string and assigns it to the Bindings field.
func (o *TeamTeamRoom) SetBindings(v []string) {
	o.Bindings = v
}

// GetDirect returns the Direct field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetDirect() bool {
	if o == nil || IsNil(o.Direct) {
		var ret bool
		return ret
	}
	return *o.Direct
}

// GetDirectOk returns a tuple with the Direct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetDirectOk() (*bool, bool) {
	if o == nil || IsNil(o.Direct) {
		return nil, false
	}
	return o.Direct, true
}

// HasDirect returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasDirect() bool {
	if o != nil && !IsNil(o.Direct) {
		return true
	}

	return false
}

// SetDirect gets a reference to the given bool and assigns it to the Direct field.
func (o *TeamTeamRoom) SetDirect(v bool) {
	o.Direct = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TeamTeamRoom) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *TeamTeamRoom) SetKind(v string) {
	o.Kind = &v
}

// GetLife returns the Life field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetLife() string {
	if o == nil || IsNil(o.Life) {
		var ret string
		return ret
	}
	return *o.Life
}

// GetLifeOk returns a tuple with the Life field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetLifeOk() (*string, bool) {
	if o == nil || IsNil(o.Life) {
		return nil, false
	}
	return o.Life, true
}

// HasLife returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasLife() bool {
	if o != nil && !IsNil(o.Life) {
		return true
	}

	return false
}

// SetLife gets a reference to the given string and assigns it to the Life field.
func (o *TeamTeamRoom) SetLife(v string) {
	o.Life = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetMembers() []string {
	if o == nil || IsNil(o.Members) {
		var ret []string
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetMembersOk() ([]string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []string and assigns it to the Members field.
func (o *TeamTeamRoom) SetMembers(v []string) {
	o.Members = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TeamTeamRoom) SetName(v string) {
	o.Name = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetPrivate() bool {
	if o == nil || IsNil(o.Private) {
		var ret bool
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetPrivateOk() (*bool, bool) {
	if o == nil || IsNil(o.Private) {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasPrivate() bool {
	if o != nil && !IsNil(o.Private) {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given bool and assigns it to the Private field.
func (o *TeamTeamRoom) SetPrivate(v bool) {
	o.Private = &v
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetSpace() string {
	if o == nil || IsNil(o.Space) {
		var ret string
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given string and assigns it to the Space field.
func (o *TeamTeamRoom) SetSpace(v string) {
	o.Space = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *TeamTeamRoom) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamRoom) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *TeamTeamRoom) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *TeamTeamRoom) SetTopic(v string) {
	o.Topic = &v
}

func (o TeamTeamRoom) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamTeamRoom) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.Bindings) {
		toSerialize["bindings"] = o.Bindings
	}
	if !IsNil(o.Direct) {
		toSerialize["direct"] = o.Direct
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Life) {
		toSerialize["life"] = o.Life
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Private) {
		toSerialize["private"] = o.Private
	}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TeamTeamRoom) UnmarshalJSON(data []byte) (err error) {
	varTeamTeamRoom := _TeamTeamRoom{}

	err = json.Unmarshal(data, &varTeamTeamRoom)

	if err != nil {
		return err
	}

	*o = TeamTeamRoom(varTeamTeamRoom)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "archived")
		delete(additionalProperties, "bindings")
		delete(additionalProperties, "direct")
		delete(additionalProperties, "id")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "life")
		delete(additionalProperties, "members")
		delete(additionalProperties, "name")
		delete(additionalProperties, "private")
		delete(additionalProperties, "space")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTeamTeamRoom struct {
	value *TeamTeamRoom
	isSet bool
}

func (v NullableTeamTeamRoom) Get() *TeamTeamRoom {
	return v.value
}

func (v *NullableTeamTeamRoom) Set(val *TeamTeamRoom) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamTeamRoom) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamTeamRoom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamTeamRoom(val *TeamTeamRoom) *NullableTeamTeamRoom {
	return &NullableTeamTeamRoom{value: val, isSet: true}
}

func (v NullableTeamTeamRoom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamTeamRoom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
