/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TeamTeamInboxAll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamTeamInboxAll{}

// TeamTeamInboxAll struct for TeamTeamInboxAll
type TeamTeamInboxAll struct {
	// Space is the space uuid. Optional for a caller in exactly one space.
	Space                *string `json:"space,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TeamTeamInboxAll TeamTeamInboxAll

// NewTeamTeamInboxAll instantiates a new TeamTeamInboxAll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamTeamInboxAll() *TeamTeamInboxAll {
	this := TeamTeamInboxAll{}
	return &this
}

// NewTeamTeamInboxAllWithDefaults instantiates a new TeamTeamInboxAll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamTeamInboxAllWithDefaults() *TeamTeamInboxAll {
	this := TeamTeamInboxAll{}
	return &this
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *TeamTeamInboxAll) GetSpace() string {
	if o == nil || IsNil(o.Space) {
		var ret string
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamInboxAll) GetSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *TeamTeamInboxAll) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given string and assigns it to the Space field.
func (o *TeamTeamInboxAll) SetSpace(v string) {
	o.Space = &v
}

func (o TeamTeamInboxAll) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamTeamInboxAll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TeamTeamInboxAll) UnmarshalJSON(data []byte) (err error) {
	varTeamTeamInboxAll := _TeamTeamInboxAll{}

	err = json.Unmarshal(data, &varTeamTeamInboxAll)

	if err != nil {
		return err
	}

	*o = TeamTeamInboxAll(varTeamTeamInboxAll)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "space")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTeamTeamInboxAll struct {
	value *TeamTeamInboxAll
	isSet bool
}

func (v NullableTeamTeamInboxAll) Get() *TeamTeamInboxAll {
	return v.value
}

func (v *NullableTeamTeamInboxAll) Set(val *TeamTeamInboxAll) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamTeamInboxAll) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamTeamInboxAll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamTeamInboxAll(val *TeamTeamInboxAll) *NullableTeamTeamInboxAll {
	return &NullableTeamTeamInboxAll{value: val, isSet: true}
}

func (v NullableTeamTeamInboxAll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamTeamInboxAll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
