/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the PatrolPatrolTenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatrolPatrolTenant{}

// PatrolPatrolTenant struct for PatrolPatrolTenant
type PatrolPatrolTenant struct {
	Brand                interface{} `json:"brand,omitempty"`
	Company              interface{} `json:"company,omitempty"`
	Features             interface{} `json:"features,omitempty"`
	Operations           interface{} `json:"operations,omitempty"`
	Terminology          interface{} `json:"terminology,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatrolPatrolTenant PatrolPatrolTenant

// NewPatrolPatrolTenant instantiates a new PatrolPatrolTenant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatrolPatrolTenant() *PatrolPatrolTenant {
	this := PatrolPatrolTenant{}
	return &this
}

// NewPatrolPatrolTenantWithDefaults instantiates a new PatrolPatrolTenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatrolPatrolTenantWithDefaults() *PatrolPatrolTenant {
	this := PatrolPatrolTenant{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatrolPatrolTenant) GetBrand() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatrolPatrolTenant) GetBrandOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return &o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *PatrolPatrolTenant) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given interface{} and assigns it to the Brand field.
func (o *PatrolPatrolTenant) SetBrand(v interface{}) {
	o.Brand = v
}

// GetCompany returns the Company field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatrolPatrolTenant) GetCompany() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatrolPatrolTenant) GetCompanyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return &o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *PatrolPatrolTenant) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given interface{} and assigns it to the Company field.
func (o *PatrolPatrolTenant) SetCompany(v interface{}) {
	o.Company = v
}

// GetFeatures returns the Features field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatrolPatrolTenant) GetFeatures() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatrolPatrolTenant) GetFeaturesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return &o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *PatrolPatrolTenant) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given interface{} and assigns it to the Features field.
func (o *PatrolPatrolTenant) SetFeatures(v interface{}) {
	o.Features = v
}

// GetOperations returns the Operations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatrolPatrolTenant) GetOperations() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatrolPatrolTenant) GetOperationsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return &o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *PatrolPatrolTenant) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given interface{} and assigns it to the Operations field.
func (o *PatrolPatrolTenant) SetOperations(v interface{}) {
	o.Operations = v
}

// GetTerminology returns the Terminology field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatrolPatrolTenant) GetTerminology() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Terminology
}

// GetTerminologyOk returns a tuple with the Terminology field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatrolPatrolTenant) GetTerminologyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Terminology) {
		return nil, false
	}
	return &o.Terminology, true
}

// HasTerminology returns a boolean if a field has been set.
func (o *PatrolPatrolTenant) HasTerminology() bool {
	if o != nil && !IsNil(o.Terminology) {
		return true
	}

	return false
}

// SetTerminology gets a reference to the given interface{} and assigns it to the Terminology field.
func (o *PatrolPatrolTenant) SetTerminology(v interface{}) {
	o.Terminology = v
}

func (o PatrolPatrolTenant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatrolPatrolTenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Brand != nil {
		toSerialize["brand"] = o.Brand
	}
	if o.Company != nil {
		toSerialize["company"] = o.Company
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	if o.Operations != nil {
		toSerialize["operations"] = o.Operations
	}
	if o.Terminology != nil {
		toSerialize["terminology"] = o.Terminology
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatrolPatrolTenant) UnmarshalJSON(data []byte) (err error) {
	varPatrolPatrolTenant := _PatrolPatrolTenant{}

	err = json.Unmarshal(data, &varPatrolPatrolTenant)

	if err != nil {
		return err
	}

	*o = PatrolPatrolTenant(varPatrolPatrolTenant)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "brand")
		delete(additionalProperties, "company")
		delete(additionalProperties, "features")
		delete(additionalProperties, "operations")
		delete(additionalProperties, "terminology")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatrolPatrolTenant struct {
	value *PatrolPatrolTenant
	isSet bool
}

func (v NullablePatrolPatrolTenant) Get() *PatrolPatrolTenant {
	return v.value
}

func (v *NullablePatrolPatrolTenant) Set(val *PatrolPatrolTenant) {
	v.value = val
	v.isSet = true
}

func (v NullablePatrolPatrolTenant) IsSet() bool {
	return v.isSet
}

func (v *NullablePatrolPatrolTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatrolPatrolTenant(val *PatrolPatrolTenant) *NullablePatrolPatrolTenant {
	return &NullablePatrolPatrolTenant{value: val, isSet: true}
}

func (v NullablePatrolPatrolTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatrolPatrolTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
