/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the NetworkIdentityList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkIdentityList{}

// NetworkIdentityList struct for NetworkIdentityList
type NetworkIdentityList struct {
	// Identities is one row per fabric identity tagged with the caller's org role.
	Identities           []NetworkIdentityView `json:"identities,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NetworkIdentityList NetworkIdentityList

// NewNetworkIdentityList instantiates a new NetworkIdentityList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkIdentityList() *NetworkIdentityList {
	this := NetworkIdentityList{}
	return &this
}

// NewNetworkIdentityListWithDefaults instantiates a new NetworkIdentityList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkIdentityListWithDefaults() *NetworkIdentityList {
	this := NetworkIdentityList{}
	return &this
}

// GetIdentities returns the Identities field value if set, zero value otherwise.
func (o *NetworkIdentityList) GetIdentities() []NetworkIdentityView {
	if o == nil || IsNil(o.Identities) {
		var ret []NetworkIdentityView
		return ret
	}
	return o.Identities
}

// GetIdentitiesOk returns a tuple with the Identities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkIdentityList) GetIdentitiesOk() ([]NetworkIdentityView, bool) {
	if o == nil || IsNil(o.Identities) {
		return nil, false
	}
	return o.Identities, true
}

// HasIdentities returns a boolean if a field has been set.
func (o *NetworkIdentityList) HasIdentities() bool {
	if o != nil && !IsNil(o.Identities) {
		return true
	}

	return false
}

// SetIdentities gets a reference to the given []NetworkIdentityView and assigns it to the Identities field.
func (o *NetworkIdentityList) SetIdentities(v []NetworkIdentityView) {
	o.Identities = v
}

func (o NetworkIdentityList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkIdentityList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identities) {
		toSerialize["identities"] = o.Identities
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkIdentityList) UnmarshalJSON(data []byte) (err error) {
	varNetworkIdentityList := _NetworkIdentityList{}

	err = json.Unmarshal(data, &varNetworkIdentityList)

	if err != nil {
		return err
	}

	*o = NetworkIdentityList(varNetworkIdentityList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkIdentityList struct {
	value *NetworkIdentityList
	isSet bool
}

func (v NullableNetworkIdentityList) Get() *NetworkIdentityList {
	return v.value
}

func (v *NullableNetworkIdentityList) Set(val *NetworkIdentityList) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkIdentityList) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkIdentityList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkIdentityList(val *NetworkIdentityList) *NullableNetworkIdentityList {
	return &NullableNetworkIdentityList{value: val, isSet: true}
}

func (v NullableNetworkIdentityList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkIdentityList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
