/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TaxMatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxMatch{}

// TaxMatch struct for TaxMatch
type TaxMatch struct {
	// At is when the payer recorded it, unix seconds.
	At *int64 `json:"at,omitempty"`
	// By is the admin who recorded it.
	By *string `json:"by,omitempty"`
	// Result is what IRS TIN Matching answered: matched or mismatched.
	Result               *string `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TaxMatch TaxMatch

// NewTaxMatch instantiates a new TaxMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxMatch() *TaxMatch {
	this := TaxMatch{}
	return &this
}

// NewTaxMatchWithDefaults instantiates a new TaxMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxMatchWithDefaults() *TaxMatch {
	this := TaxMatch{}
	return &this
}

// GetAt returns the At field value if set, zero value otherwise.
func (o *TaxMatch) GetAt() int64 {
	if o == nil || IsNil(o.At) {
		var ret int64
		return ret
	}
	return *o.At
}

// GetAtOk returns a tuple with the At field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxMatch) GetAtOk() (*int64, bool) {
	if o == nil || IsNil(o.At) {
		return nil, false
	}
	return o.At, true
}

// HasAt returns a boolean if a field has been set.
func (o *TaxMatch) HasAt() bool {
	if o != nil && !IsNil(o.At) {
		return true
	}

	return false
}

// SetAt gets a reference to the given int64 and assigns it to the At field.
func (o *TaxMatch) SetAt(v int64) {
	o.At = &v
}

// GetBy returns the By field value if set, zero value otherwise.
func (o *TaxMatch) GetBy() string {
	if o == nil || IsNil(o.By) {
		var ret string
		return ret
	}
	return *o.By
}

// GetByOk returns a tuple with the By field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxMatch) GetByOk() (*string, bool) {
	if o == nil || IsNil(o.By) {
		return nil, false
	}
	return o.By, true
}

// HasBy returns a boolean if a field has been set.
func (o *TaxMatch) HasBy() bool {
	if o != nil && !IsNil(o.By) {
		return true
	}

	return false
}

// SetBy gets a reference to the given string and assigns it to the By field.
func (o *TaxMatch) SetBy(v string) {
	o.By = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TaxMatch) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxMatch) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TaxMatch) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *TaxMatch) SetResult(v string) {
	o.Result = &v
}

func (o TaxMatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxMatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.At) {
		toSerialize["at"] = o.At
	}
	if !IsNil(o.By) {
		toSerialize["by"] = o.By
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TaxMatch) UnmarshalJSON(data []byte) (err error) {
	varTaxMatch := _TaxMatch{}

	err = json.Unmarshal(data, &varTaxMatch)

	if err != nil {
		return err
	}

	*o = TaxMatch(varTaxMatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "at")
		delete(additionalProperties, "by")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTaxMatch struct {
	value *TaxMatch
	isSet bool
}

func (v NullableTaxMatch) Get() *TaxMatch {
	return v.value
}

func (v *NullableTaxMatch) Set(val *TaxMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxMatch(val *TaxMatch) *NullableTaxMatch {
	return &NullableTaxMatch{value: val, isSet: true}
}

func (v NullableTaxMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
