/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the MarketplaceDeliverIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceDeliverIn{}

// MarketplaceDeliverIn struct for MarketplaceDeliverIn
type MarketplaceDeliverIn struct {
	// Hash is the seller's own commitment to what was delivered, 32 bytes as 0x hex; the SHA-256 of the note and URL when empty.
	Hash *string `json:"hash,omitempty"`
	// ID is the job, from the path.
	Id *string `json:"id,omitempty"`
	// Note says what was delivered. Required, at most 4096 characters.
	Note *string `json:"note,omitempty"`
	// URL is where it is, https.
	Url                  *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketplaceDeliverIn MarketplaceDeliverIn

// NewMarketplaceDeliverIn instantiates a new MarketplaceDeliverIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceDeliverIn() *MarketplaceDeliverIn {
	this := MarketplaceDeliverIn{}
	return &this
}

// NewMarketplaceDeliverInWithDefaults instantiates a new MarketplaceDeliverIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceDeliverInWithDefaults() *MarketplaceDeliverIn {
	this := MarketplaceDeliverIn{}
	return &this
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *MarketplaceDeliverIn) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDeliverIn) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *MarketplaceDeliverIn) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *MarketplaceDeliverIn) SetHash(v string) {
	o.Hash = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MarketplaceDeliverIn) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDeliverIn) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MarketplaceDeliverIn) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MarketplaceDeliverIn) SetId(v string) {
	o.Id = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *MarketplaceDeliverIn) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDeliverIn) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *MarketplaceDeliverIn) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *MarketplaceDeliverIn) SetNote(v string) {
	o.Note = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *MarketplaceDeliverIn) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDeliverIn) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *MarketplaceDeliverIn) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *MarketplaceDeliverIn) SetUrl(v string) {
	o.Url = &v
}

func (o MarketplaceDeliverIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceDeliverIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketplaceDeliverIn) UnmarshalJSON(data []byte) (err error) {
	varMarketplaceDeliverIn := _MarketplaceDeliverIn{}

	err = json.Unmarshal(data, &varMarketplaceDeliverIn)

	if err != nil {
		return err
	}

	*o = MarketplaceDeliverIn(varMarketplaceDeliverIn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hash")
		delete(additionalProperties, "id")
		delete(additionalProperties, "note")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketplaceDeliverIn struct {
	value *MarketplaceDeliverIn
	isSet bool
}

func (v NullableMarketplaceDeliverIn) Get() *MarketplaceDeliverIn {
	return v.value
}

func (v *NullableMarketplaceDeliverIn) Set(val *MarketplaceDeliverIn) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceDeliverIn) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceDeliverIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceDeliverIn(val *MarketplaceDeliverIn) *NullableMarketplaceDeliverIn {
	return &NullableMarketplaceDeliverIn{value: val, isSet: true}
}

func (v NullableMarketplaceDeliverIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceDeliverIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
