/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the ComplianceHealthView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComplianceHealthView{}

// ComplianceHealthView struct for ComplianceHealthView
type ComplianceHealthView struct {
	// Provider is the wired verification provider's name (\"manual\" by default).
	Provider *string `json:"provider,omitempty"`
	// Status is \"ok\" when the subsystem is live.
	Status               *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ComplianceHealthView ComplianceHealthView

// NewComplianceHealthView instantiates a new ComplianceHealthView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComplianceHealthView() *ComplianceHealthView {
	this := ComplianceHealthView{}
	return &this
}

// NewComplianceHealthViewWithDefaults instantiates a new ComplianceHealthView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComplianceHealthViewWithDefaults() *ComplianceHealthView {
	this := ComplianceHealthView{}
	return &this
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ComplianceHealthView) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceHealthView) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ComplianceHealthView) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ComplianceHealthView) SetProvider(v string) {
	o.Provider = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ComplianceHealthView) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComplianceHealthView) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ComplianceHealthView) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ComplianceHealthView) SetStatus(v string) {
	o.Status = &v
}

func (o ComplianceHealthView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComplianceHealthView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ComplianceHealthView) UnmarshalJSON(data []byte) (err error) {
	varComplianceHealthView := _ComplianceHealthView{}

	err = json.Unmarshal(data, &varComplianceHealthView)

	if err != nil {
		return err
	}

	*o = ComplianceHealthView(varComplianceHealthView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "provider")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableComplianceHealthView struct {
	value *ComplianceHealthView
	isSet bool
}

func (v NullableComplianceHealthView) Get() *ComplianceHealthView {
	return v.value
}

func (v *NullableComplianceHealthView) Set(val *ComplianceHealthView) {
	v.value = val
	v.isSet = true
}

func (v NullableComplianceHealthView) IsSet() bool {
	return v.isSet
}

func (v *NullableComplianceHealthView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComplianceHealthView(val *ComplianceHealthView) *NullableComplianceHealthView {
	return &NullableComplianceHealthView{value: val, isSet: true}
}

func (v NullableComplianceHealthView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComplianceHealthView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
