/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TrustClauseRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustClauseRow{}

// TrustClauseRow struct for TrustClauseRow
type TrustClauseRow struct {
	// Controls are the ids behind it, strongest first. Empty when nothing covers it — and an absent control is never listed here, however it maps.
	Controls []string `json:"controls,omitempty"`
	// Group is the clause's section within the standard, when it has one.
	Group *string `json:"group,omitempty"`
	// ID is the clause id as the standard publishes it — \"CC6.1\", \"A.5.15\", \"AC\".
	Id *string `json:"id,omitempty"`
	// Level is what the strongest control pointed at this clause is worth: \"automated\", \"partial\" or \"none\".
	Level *string `json:"level,omitempty"`
	// Title is the standard's own words for that clause.
	Title                *string `json:"title,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TrustClauseRow TrustClauseRow

// NewTrustClauseRow instantiates a new TrustClauseRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustClauseRow() *TrustClauseRow {
	this := TrustClauseRow{}
	return &this
}

// NewTrustClauseRowWithDefaults instantiates a new TrustClauseRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustClauseRowWithDefaults() *TrustClauseRow {
	this := TrustClauseRow{}
	return &this
}

// GetControls returns the Controls field value if set, zero value otherwise.
func (o *TrustClauseRow) GetControls() []string {
	if o == nil || IsNil(o.Controls) {
		var ret []string
		return ret
	}
	return o.Controls
}

// GetControlsOk returns a tuple with the Controls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustClauseRow) GetControlsOk() ([]string, bool) {
	if o == nil || IsNil(o.Controls) {
		return nil, false
	}
	return o.Controls, true
}

// HasControls returns a boolean if a field has been set.
func (o *TrustClauseRow) HasControls() bool {
	if o != nil && !IsNil(o.Controls) {
		return true
	}

	return false
}

// SetControls gets a reference to the given []string and assigns it to the Controls field.
func (o *TrustClauseRow) SetControls(v []string) {
	o.Controls = v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *TrustClauseRow) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustClauseRow) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *TrustClauseRow) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *TrustClauseRow) SetGroup(v string) {
	o.Group = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TrustClauseRow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustClauseRow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TrustClauseRow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TrustClauseRow) SetId(v string) {
	o.Id = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *TrustClauseRow) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustClauseRow) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *TrustClauseRow) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *TrustClauseRow) SetLevel(v string) {
	o.Level = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *TrustClauseRow) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustClauseRow) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *TrustClauseRow) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *TrustClauseRow) SetTitle(v string) {
	o.Title = &v
}

func (o TrustClauseRow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustClauseRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Controls) {
		toSerialize["controls"] = o.Controls
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TrustClauseRow) UnmarshalJSON(data []byte) (err error) {
	varTrustClauseRow := _TrustClauseRow{}

	err = json.Unmarshal(data, &varTrustClauseRow)

	if err != nil {
		return err
	}

	*o = TrustClauseRow(varTrustClauseRow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "controls")
		delete(additionalProperties, "group")
		delete(additionalProperties, "id")
		delete(additionalProperties, "level")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTrustClauseRow struct {
	value *TrustClauseRow
	isSet bool
}

func (v NullableTrustClauseRow) Get() *TrustClauseRow {
	return v.value
}

func (v *NullableTrustClauseRow) Set(val *TrustClauseRow) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustClauseRow) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustClauseRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustClauseRow(val *TrustClauseRow) *NullableTrustClauseRow {
	return &NullableTrustClauseRow{value: val, isSet: true}
}

func (v NullableTrustClauseRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustClauseRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
