/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the SocialSocialAccountWrite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocialSocialAccountWrite{}

// SocialSocialAccountWrite struct for SocialSocialAccountWrite
type SocialSocialAccountWrite struct {
	// Handle is the account's public name on the network. Omitting it BLANKS the stored handle: this is a replacement, not a merge.  Example: \"@acme\"
	Handle *string `json:"handle,omitempty"`
	// Provider is the network this account is on: x, facebook, instagram, linkedin, tiktok, youtube or threads. Omitted means x.  Example: \"x\"
	Provider *string `json:"provider,omitempty"`
	// Status is the connection lifecycle: connected, disconnected or error. Omitting it RESETS the account to connected.
	Status               *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SocialSocialAccountWrite SocialSocialAccountWrite

// NewSocialSocialAccountWrite instantiates a new SocialSocialAccountWrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocialSocialAccountWrite() *SocialSocialAccountWrite {
	this := SocialSocialAccountWrite{}
	return &this
}

// NewSocialSocialAccountWriteWithDefaults instantiates a new SocialSocialAccountWrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocialSocialAccountWriteWithDefaults() *SocialSocialAccountWrite {
	this := SocialSocialAccountWrite{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *SocialSocialAccountWrite) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialSocialAccountWrite) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *SocialSocialAccountWrite) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *SocialSocialAccountWrite) SetHandle(v string) {
	o.Handle = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *SocialSocialAccountWrite) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialSocialAccountWrite) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *SocialSocialAccountWrite) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *SocialSocialAccountWrite) SetProvider(v string) {
	o.Provider = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SocialSocialAccountWrite) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialSocialAccountWrite) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SocialSocialAccountWrite) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SocialSocialAccountWrite) SetStatus(v string) {
	o.Status = &v
}

func (o SocialSocialAccountWrite) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocialSocialAccountWrite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SocialSocialAccountWrite) UnmarshalJSON(data []byte) (err error) {
	varSocialSocialAccountWrite := _SocialSocialAccountWrite{}

	err = json.Unmarshal(data, &varSocialSocialAccountWrite)

	if err != nil {
		return err
	}

	*o = SocialSocialAccountWrite(varSocialSocialAccountWrite)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "handle")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSocialSocialAccountWrite struct {
	value *SocialSocialAccountWrite
	isSet bool
}

func (v NullableSocialSocialAccountWrite) Get() *SocialSocialAccountWrite {
	return v.value
}

func (v *NullableSocialSocialAccountWrite) Set(val *SocialSocialAccountWrite) {
	v.value = val
	v.isSet = true
}

func (v NullableSocialSocialAccountWrite) IsSet() bool {
	return v.isSet
}

func (v *NullableSocialSocialAccountWrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocialSocialAccountWrite(val *SocialSocialAccountWrite) *NullableSocialSocialAccountWrite {
	return &NullableSocialSocialAccountWrite{value: val, isSet: true}
}

func (v NullableSocialSocialAccountWrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocialSocialAccountWrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
