/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the DataroomTrustPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataroomTrustPage{}

// DataroomTrustPage struct for DataroomTrustPage
type DataroomTrustPage struct {
	// Items is everything the centre publishes: what can be read now, and what exists and is released on request.
	Items []DataroomTrustItem `json:"items,omitempty"`
	// Name is the org's display name for its centre.
	Name *string `json:"name,omitempty"`
	// Nda is the text a party must accept to ask for the gated items, verbatim. Empty when the org asks for none.
	Nda *string `json:"nda,omitempty"`
	// Slug is the centre's public address.
	Slug                 *string `json:"slug,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataroomTrustPage DataroomTrustPage

// NewDataroomTrustPage instantiates a new DataroomTrustPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataroomTrustPage() *DataroomTrustPage {
	this := DataroomTrustPage{}
	return &this
}

// NewDataroomTrustPageWithDefaults instantiates a new DataroomTrustPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataroomTrustPageWithDefaults() *DataroomTrustPage {
	this := DataroomTrustPage{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DataroomTrustPage) GetItems() []DataroomTrustItem {
	if o == nil || IsNil(o.Items) {
		var ret []DataroomTrustItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataroomTrustPage) GetItemsOk() ([]DataroomTrustItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DataroomTrustPage) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DataroomTrustItem and assigns it to the Items field.
func (o *DataroomTrustPage) SetItems(v []DataroomTrustItem) {
	o.Items = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DataroomTrustPage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataroomTrustPage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DataroomTrustPage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DataroomTrustPage) SetName(v string) {
	o.Name = &v
}

// GetNda returns the Nda field value if set, zero value otherwise.
func (o *DataroomTrustPage) GetNda() string {
	if o == nil || IsNil(o.Nda) {
		var ret string
		return ret
	}
	return *o.Nda
}

// GetNdaOk returns a tuple with the Nda field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataroomTrustPage) GetNdaOk() (*string, bool) {
	if o == nil || IsNil(o.Nda) {
		return nil, false
	}
	return o.Nda, true
}

// HasNda returns a boolean if a field has been set.
func (o *DataroomTrustPage) HasNda() bool {
	if o != nil && !IsNil(o.Nda) {
		return true
	}

	return false
}

// SetNda gets a reference to the given string and assigns it to the Nda field.
func (o *DataroomTrustPage) SetNda(v string) {
	o.Nda = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *DataroomTrustPage) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataroomTrustPage) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *DataroomTrustPage) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *DataroomTrustPage) SetSlug(v string) {
	o.Slug = &v
}

func (o DataroomTrustPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataroomTrustPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Nda) {
		toSerialize["nda"] = o.Nda
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataroomTrustPage) UnmarshalJSON(data []byte) (err error) {
	varDataroomTrustPage := _DataroomTrustPage{}

	err = json.Unmarshal(data, &varDataroomTrustPage)

	if err != nil {
		return err
	}

	*o = DataroomTrustPage(varDataroomTrustPage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "name")
		delete(additionalProperties, "nda")
		delete(additionalProperties, "slug")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataroomTrustPage struct {
	value *DataroomTrustPage
	isSet bool
}

func (v NullableDataroomTrustPage) Get() *DataroomTrustPage {
	return v.value
}

func (v *NullableDataroomTrustPage) Set(val *DataroomTrustPage) {
	v.value = val
	v.isSet = true
}

func (v NullableDataroomTrustPage) IsSet() bool {
	return v.isSet
}

func (v *NullableDataroomTrustPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataroomTrustPage(val *DataroomTrustPage) *NullableDataroomTrustPage {
	return &NullableDataroomTrustPage{value: val, isSet: true}
}

func (v NullableDataroomTrustPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataroomTrustPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
