/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the PrincipalFounder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalFounder{}

// PrincipalFounder struct for PrincipalFounder
type PrincipalFounder struct {
	// EquityBps is ownership in basis points, 0–10000.
	EquityBps *int64 `json:"equityBps,omitempty"`
	// KYC is pending, verified, reviewer_confirmed or failed, verbatim.
	Kyc *string `json:"kyc,omitempty"`
	// Name is the full legal name.
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalFounder PrincipalFounder

// NewPrincipalFounder instantiates a new PrincipalFounder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalFounder() *PrincipalFounder {
	this := PrincipalFounder{}
	return &this
}

// NewPrincipalFounderWithDefaults instantiates a new PrincipalFounder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalFounderWithDefaults() *PrincipalFounder {
	this := PrincipalFounder{}
	return &this
}

// GetEquityBps returns the EquityBps field value if set, zero value otherwise.
func (o *PrincipalFounder) GetEquityBps() int64 {
	if o == nil || IsNil(o.EquityBps) {
		var ret int64
		return ret
	}
	return *o.EquityBps
}

// GetEquityBpsOk returns a tuple with the EquityBps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalFounder) GetEquityBpsOk() (*int64, bool) {
	if o == nil || IsNil(o.EquityBps) {
		return nil, false
	}
	return o.EquityBps, true
}

// HasEquityBps returns a boolean if a field has been set.
func (o *PrincipalFounder) HasEquityBps() bool {
	if o != nil && !IsNil(o.EquityBps) {
		return true
	}

	return false
}

// SetEquityBps gets a reference to the given int64 and assigns it to the EquityBps field.
func (o *PrincipalFounder) SetEquityBps(v int64) {
	o.EquityBps = &v
}

// GetKyc returns the Kyc field value if set, zero value otherwise.
func (o *PrincipalFounder) GetKyc() string {
	if o == nil || IsNil(o.Kyc) {
		var ret string
		return ret
	}
	return *o.Kyc
}

// GetKycOk returns a tuple with the Kyc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalFounder) GetKycOk() (*string, bool) {
	if o == nil || IsNil(o.Kyc) {
		return nil, false
	}
	return o.Kyc, true
}

// HasKyc returns a boolean if a field has been set.
func (o *PrincipalFounder) HasKyc() bool {
	if o != nil && !IsNil(o.Kyc) {
		return true
	}

	return false
}

// SetKyc gets a reference to the given string and assigns it to the Kyc field.
func (o *PrincipalFounder) SetKyc(v string) {
	o.Kyc = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PrincipalFounder) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalFounder) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PrincipalFounder) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PrincipalFounder) SetName(v string) {
	o.Name = &v
}

func (o PrincipalFounder) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalFounder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EquityBps) {
		toSerialize["equityBps"] = o.EquityBps
	}
	if !IsNil(o.Kyc) {
		toSerialize["kyc"] = o.Kyc
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalFounder) UnmarshalJSON(data []byte) (err error) {
	varPrincipalFounder := _PrincipalFounder{}

	err = json.Unmarshal(data, &varPrincipalFounder)

	if err != nil {
		return err
	}

	*o = PrincipalFounder(varPrincipalFounder)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "equityBps")
		delete(additionalProperties, "kyc")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalFounder struct {
	value *PrincipalFounder
	isSet bool
}

func (v NullablePrincipalFounder) Get() *PrincipalFounder {
	return v.value
}

func (v *NullablePrincipalFounder) Set(val *PrincipalFounder) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalFounder) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalFounder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalFounder(val *PrincipalFounder) *NullablePrincipalFounder {
	return &NullablePrincipalFounder{value: val, isSet: true}
}

func (v NullablePrincipalFounder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalFounder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
