/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the PrincipalJWKS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalJWKS{}

// PrincipalJWKS struct for PrincipalJWKS
type PrincipalJWKS struct {
	Keys                 []PrincipalJWK `json:"keys,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalJWKS PrincipalJWKS

// NewPrincipalJWKS instantiates a new PrincipalJWKS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalJWKS() *PrincipalJWKS {
	this := PrincipalJWKS{}
	return &this
}

// NewPrincipalJWKSWithDefaults instantiates a new PrincipalJWKS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalJWKSWithDefaults() *PrincipalJWKS {
	this := PrincipalJWKS{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *PrincipalJWKS) GetKeys() []PrincipalJWK {
	if o == nil || IsNil(o.Keys) {
		var ret []PrincipalJWK
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalJWKS) GetKeysOk() ([]PrincipalJWK, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *PrincipalJWKS) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []PrincipalJWK and assigns it to the Keys field.
func (o *PrincipalJWKS) SetKeys(v []PrincipalJWK) {
	o.Keys = v
}

func (o PrincipalJWKS) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalJWKS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalJWKS) UnmarshalJSON(data []byte) (err error) {
	varPrincipalJWKS := _PrincipalJWKS{}

	err = json.Unmarshal(data, &varPrincipalJWKS)

	if err != nil {
		return err
	}

	*o = PrincipalJWKS(varPrincipalJWKS)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "keys")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalJWKS struct {
	value *PrincipalJWKS
	isSet bool
}

func (v NullablePrincipalJWKS) Get() *PrincipalJWKS {
	return v.value
}

func (v *NullablePrincipalJWKS) Set(val *PrincipalJWKS) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalJWKS) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalJWKS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalJWKS(val *PrincipalJWKS) *NullablePrincipalJWKS {
	return &NullablePrincipalJWKS{value: val, isSet: true}
}

func (v NullablePrincipalJWKS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalJWKS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
