/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the AutoConnectorMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoConnectorMetadata{}

// AutoConnectorMetadata struct for AutoConnectorMetadata
type AutoConnectorMetadata struct {
	Actions     []AutoConnectorAction `json:"actions,omitempty"`
	Auth        *AutoConnectorAuth    `json:"auth,omitempty"`
	Categories  []string              `json:"categories,omitempty"`
	Description *string               `json:"description,omitempty"`
	DisplayName *string               `json:"displayName,omitempty"`
	LogoUrl     *string               `json:"logoUrl,omitempty"`
	Name        *string               `json:"name,omitempty"`
	// Runnable is whether this connector's actions run HERE, so a caller can invoke what the entry lists. It is the registry's answer — an action registered for the connector — never a stored flag, because a stored flag is a second answer to a question the registry already answers.
	Runnable             *bool                  `json:"runnable,omitempty"`
	Triggers             []AutoConnectorTrigger `json:"triggers,omitempty"`
	Version              *string                `json:"version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AutoConnectorMetadata AutoConnectorMetadata

// NewAutoConnectorMetadata instantiates a new AutoConnectorMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoConnectorMetadata() *AutoConnectorMetadata {
	this := AutoConnectorMetadata{}
	return &this
}

// NewAutoConnectorMetadataWithDefaults instantiates a new AutoConnectorMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoConnectorMetadataWithDefaults() *AutoConnectorMetadata {
	this := AutoConnectorMetadata{}
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetActions() []AutoConnectorAction {
	if o == nil || IsNil(o.Actions) {
		var ret []AutoConnectorAction
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetActionsOk() ([]AutoConnectorAction, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []AutoConnectorAction and assigns it to the Actions field.
func (o *AutoConnectorMetadata) SetActions(v []AutoConnectorAction) {
	o.Actions = v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetAuth() AutoConnectorAuth {
	if o == nil || IsNil(o.Auth) {
		var ret AutoConnectorAuth
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetAuthOk() (*AutoConnectorAuth, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given AutoConnectorAuth and assigns it to the Auth field.
func (o *AutoConnectorMetadata) SetAuth(v AutoConnectorAuth) {
	o.Auth = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *AutoConnectorMetadata) SetCategories(v []string) {
	o.Categories = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AutoConnectorMetadata) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *AutoConnectorMetadata) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *AutoConnectorMetadata) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AutoConnectorMetadata) SetName(v string) {
	o.Name = &v
}

// GetRunnable returns the Runnable field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetRunnable() bool {
	if o == nil || IsNil(o.Runnable) {
		var ret bool
		return ret
	}
	return *o.Runnable
}

// GetRunnableOk returns a tuple with the Runnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetRunnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Runnable) {
		return nil, false
	}
	return o.Runnable, true
}

// HasRunnable returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasRunnable() bool {
	if o != nil && !IsNil(o.Runnable) {
		return true
	}

	return false
}

// SetRunnable gets a reference to the given bool and assigns it to the Runnable field.
func (o *AutoConnectorMetadata) SetRunnable(v bool) {
	o.Runnable = &v
}

// GetTriggers returns the Triggers field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetTriggers() []AutoConnectorTrigger {
	if o == nil || IsNil(o.Triggers) {
		var ret []AutoConnectorTrigger
		return ret
	}
	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetTriggersOk() ([]AutoConnectorTrigger, bool) {
	if o == nil || IsNil(o.Triggers) {
		return nil, false
	}
	return o.Triggers, true
}

// HasTriggers returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasTriggers() bool {
	if o != nil && !IsNil(o.Triggers) {
		return true
	}

	return false
}

// SetTriggers gets a reference to the given []AutoConnectorTrigger and assigns it to the Triggers field.
func (o *AutoConnectorMetadata) SetTriggers(v []AutoConnectorTrigger) {
	o.Triggers = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AutoConnectorMetadata) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoConnectorMetadata) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AutoConnectorMetadata) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *AutoConnectorMetadata) SetVersion(v string) {
	o.Version = &v
}

func (o AutoConnectorMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoConnectorMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.LogoUrl) {
		toSerialize["logoUrl"] = o.LogoUrl
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Runnable) {
		toSerialize["runnable"] = o.Runnable
	}
	if !IsNil(o.Triggers) {
		toSerialize["triggers"] = o.Triggers
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AutoConnectorMetadata) UnmarshalJSON(data []byte) (err error) {
	varAutoConnectorMetadata := _AutoConnectorMetadata{}

	err = json.Unmarshal(data, &varAutoConnectorMetadata)

	if err != nil {
		return err
	}

	*o = AutoConnectorMetadata(varAutoConnectorMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		delete(additionalProperties, "auth")
		delete(additionalProperties, "categories")
		delete(additionalProperties, "description")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "logoUrl")
		delete(additionalProperties, "name")
		delete(additionalProperties, "runnable")
		delete(additionalProperties, "triggers")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAutoConnectorMetadata struct {
	value *AutoConnectorMetadata
	isSet bool
}

func (v NullableAutoConnectorMetadata) Get() *AutoConnectorMetadata {
	return v.value
}

func (v *NullableAutoConnectorMetadata) Set(val *AutoConnectorMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoConnectorMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoConnectorMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoConnectorMetadata(val *AutoConnectorMetadata) *NullableAutoConnectorMetadata {
	return &NullableAutoConnectorMetadata{value: val, isSet: true}
}

func (v NullableAutoConnectorMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoConnectorMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
