/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the RiskRiskSearchReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskRiskSearchReport{}

// RiskRiskSearchReport struct for RiskRiskSearchReport
type RiskRiskSearchReport struct {
	// Done is false while the run is still going; the trials below are then the ones finished so far.
	Done *bool `json:"done,omitempty"`
	// Ended is when it finished, RFC 3339. Absent while it is still going.
	Ended *string `json:"ended,omitempty"`
	// Events is how much of this organisation's history was replayed.
	Events *int64 `json:"events,omitempty"`
	// Fitted is the winning shape FITTED over your own history and published as one of your organisation's own model values. Name its address on PUT /v1/risk/state/model and the winning shape becomes the model you are running.  It is why this op answers something you can act on. A trial keeps counts and not the model that produced them, so a report without this named a shape nobody could install — and the adoption path refused a shape change besides. Fitting the winner once is a sixty-fifth pass over the same history; keeping all sixty-four fitted models resident instead would cost a measured 21 MiB per run for sixty-three shapes nobody adopts.  Two things about it are worth knowing before you adopt it. Its realised rate can differ from the winner's above, because the ranking measures every candidate under one fixed reference geometry so the comparison is a comparison, while this is fitted under YOUR geometry — the one an outsider cannot predict. And it has learned the window this search replayed and nothing older, so adopting it trades history for fit.
	Fitted *RiskRiskModelValue `json:"fitted,omitempty"`
	// Gap says why the winning shape could not be fitted into an adoptable value, when it could not. It is separate from Refusal because they are different facts: a refusal means the ranking below proves nothing, a gap means the ranking stands and only the value is missing.
	Gap *string `json:"gap,omitempty"`
	// ID is the run.
	Id *string `json:"id,omitempty"`
	// Refusal says why the run proves nothing, when it does. An empty history is REFUSED rather than reported as zero alerts: \"no alerts\" is exactly what a quiet model looks like, and choosing a shape on the strength of an empty replay is the failure a sandbox exists to prevent.
	Refusal *string `json:"refusal,omitempty"`
	// Started is when the run was accepted, RFC 3339.
	Started *string `json:"started,omitempty"`
	// Trials is every shape tried, best first.
	Trials []RiskRiskTrial `json:"trials,omitempty"`
	// Winner is the best-fitting shape, absent when nothing fit.
	Winner               *RiskRiskTrial `json:"winner,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskRiskSearchReport RiskRiskSearchReport

// NewRiskRiskSearchReport instantiates a new RiskRiskSearchReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskRiskSearchReport() *RiskRiskSearchReport {
	this := RiskRiskSearchReport{}
	return &this
}

// NewRiskRiskSearchReportWithDefaults instantiates a new RiskRiskSearchReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskRiskSearchReportWithDefaults() *RiskRiskSearchReport {
	this := RiskRiskSearchReport{}
	return &this
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetDone() bool {
	if o == nil || IsNil(o.Done) {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *RiskRiskSearchReport) SetDone(v bool) {
	o.Done = &v
}

// GetEnded returns the Ended field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetEnded() string {
	if o == nil || IsNil(o.Ended) {
		var ret string
		return ret
	}
	return *o.Ended
}

// GetEndedOk returns a tuple with the Ended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetEndedOk() (*string, bool) {
	if o == nil || IsNil(o.Ended) {
		return nil, false
	}
	return o.Ended, true
}

// HasEnded returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasEnded() bool {
	if o != nil && !IsNil(o.Ended) {
		return true
	}

	return false
}

// SetEnded gets a reference to the given string and assigns it to the Ended field.
func (o *RiskRiskSearchReport) SetEnded(v string) {
	o.Ended = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetEvents() int64 {
	if o == nil || IsNil(o.Events) {
		var ret int64
		return ret
	}
	return *o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetEventsOk() (*int64, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given int64 and assigns it to the Events field.
func (o *RiskRiskSearchReport) SetEvents(v int64) {
	o.Events = &v
}

// GetFitted returns the Fitted field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetFitted() RiskRiskModelValue {
	if o == nil || IsNil(o.Fitted) {
		var ret RiskRiskModelValue
		return ret
	}
	return *o.Fitted
}

// GetFittedOk returns a tuple with the Fitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetFittedOk() (*RiskRiskModelValue, bool) {
	if o == nil || IsNil(o.Fitted) {
		return nil, false
	}
	return o.Fitted, true
}

// HasFitted returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasFitted() bool {
	if o != nil && !IsNil(o.Fitted) {
		return true
	}

	return false
}

// SetFitted gets a reference to the given RiskRiskModelValue and assigns it to the Fitted field.
func (o *RiskRiskSearchReport) SetFitted(v RiskRiskModelValue) {
	o.Fitted = &v
}

// GetGap returns the Gap field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetGap() string {
	if o == nil || IsNil(o.Gap) {
		var ret string
		return ret
	}
	return *o.Gap
}

// GetGapOk returns a tuple with the Gap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetGapOk() (*string, bool) {
	if o == nil || IsNil(o.Gap) {
		return nil, false
	}
	return o.Gap, true
}

// HasGap returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasGap() bool {
	if o != nil && !IsNil(o.Gap) {
		return true
	}

	return false
}

// SetGap gets a reference to the given string and assigns it to the Gap field.
func (o *RiskRiskSearchReport) SetGap(v string) {
	o.Gap = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RiskRiskSearchReport) SetId(v string) {
	o.Id = &v
}

// GetRefusal returns the Refusal field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetRefusal() string {
	if o == nil || IsNil(o.Refusal) {
		var ret string
		return ret
	}
	return *o.Refusal
}

// GetRefusalOk returns a tuple with the Refusal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetRefusalOk() (*string, bool) {
	if o == nil || IsNil(o.Refusal) {
		return nil, false
	}
	return o.Refusal, true
}

// HasRefusal returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasRefusal() bool {
	if o != nil && !IsNil(o.Refusal) {
		return true
	}

	return false
}

// SetRefusal gets a reference to the given string and assigns it to the Refusal field.
func (o *RiskRiskSearchReport) SetRefusal(v string) {
	o.Refusal = &v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetStarted() string {
	if o == nil || IsNil(o.Started) {
		var ret string
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetStartedOk() (*string, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given string and assigns it to the Started field.
func (o *RiskRiskSearchReport) SetStarted(v string) {
	o.Started = &v
}

// GetTrials returns the Trials field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetTrials() []RiskRiskTrial {
	if o == nil || IsNil(o.Trials) {
		var ret []RiskRiskTrial
		return ret
	}
	return o.Trials
}

// GetTrialsOk returns a tuple with the Trials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetTrialsOk() ([]RiskRiskTrial, bool) {
	if o == nil || IsNil(o.Trials) {
		return nil, false
	}
	return o.Trials, true
}

// HasTrials returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasTrials() bool {
	if o != nil && !IsNil(o.Trials) {
		return true
	}

	return false
}

// SetTrials gets a reference to the given []RiskRiskTrial and assigns it to the Trials field.
func (o *RiskRiskSearchReport) SetTrials(v []RiskRiskTrial) {
	o.Trials = v
}

// GetWinner returns the Winner field value if set, zero value otherwise.
func (o *RiskRiskSearchReport) GetWinner() RiskRiskTrial {
	if o == nil || IsNil(o.Winner) {
		var ret RiskRiskTrial
		return ret
	}
	return *o.Winner
}

// GetWinnerOk returns a tuple with the Winner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskRiskSearchReport) GetWinnerOk() (*RiskRiskTrial, bool) {
	if o == nil || IsNil(o.Winner) {
		return nil, false
	}
	return o.Winner, true
}

// HasWinner returns a boolean if a field has been set.
func (o *RiskRiskSearchReport) HasWinner() bool {
	if o != nil && !IsNil(o.Winner) {
		return true
	}

	return false
}

// SetWinner gets a reference to the given RiskRiskTrial and assigns it to the Winner field.
func (o *RiskRiskSearchReport) SetWinner(v RiskRiskTrial) {
	o.Winner = &v
}

func (o RiskRiskSearchReport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskRiskSearchReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	if !IsNil(o.Ended) {
		toSerialize["ended"] = o.Ended
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Fitted) {
		toSerialize["fitted"] = o.Fitted
	}
	if !IsNil(o.Gap) {
		toSerialize["gap"] = o.Gap
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Refusal) {
		toSerialize["refusal"] = o.Refusal
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	if !IsNil(o.Trials) {
		toSerialize["trials"] = o.Trials
	}
	if !IsNil(o.Winner) {
		toSerialize["winner"] = o.Winner
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskRiskSearchReport) UnmarshalJSON(data []byte) (err error) {
	varRiskRiskSearchReport := _RiskRiskSearchReport{}

	err = json.Unmarshal(data, &varRiskRiskSearchReport)

	if err != nil {
		return err
	}

	*o = RiskRiskSearchReport(varRiskRiskSearchReport)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "done")
		delete(additionalProperties, "ended")
		delete(additionalProperties, "events")
		delete(additionalProperties, "fitted")
		delete(additionalProperties, "gap")
		delete(additionalProperties, "id")
		delete(additionalProperties, "refusal")
		delete(additionalProperties, "started")
		delete(additionalProperties, "trials")
		delete(additionalProperties, "winner")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskRiskSearchReport struct {
	value *RiskRiskSearchReport
	isSet bool
}

func (v NullableRiskRiskSearchReport) Get() *RiskRiskSearchReport {
	return v.value
}

func (v *NullableRiskRiskSearchReport) Set(val *RiskRiskSearchReport) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskRiskSearchReport) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskRiskSearchReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskRiskSearchReport(val *RiskRiskSearchReport) *NullableRiskRiskSearchReport {
	return &NullableRiskRiskSearchReport{value: val, isSet: true}
}

func (v NullableRiskRiskSearchReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskRiskSearchReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
