/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the ChannelInboxView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelInboxView{}

// ChannelInboxView struct for ChannelInboxView
type ChannelInboxView struct {
	// Account is the lowercased external id of the org's connected account on that transport: the Discord guild id, the Slack team id, the Teams AAD tenant id, or the bound Telegram chat id. Informational only — the gate keys on (org, channel), never on the account.
	Account *string `json:"account,omitempty"`
	// Channel is the transport this message arrived on — discord, slack, teams or telegram — and the `:channel` segment to reply through.
	Channel *string `json:"channel,omitempty"`
	// CreatedAt is Unix SECONDS, stamped by the ingest goroutine when the message was accepted — not the transport's own send time. Rows are dropped 30 days after it.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// ID is the store's row id, assigned on insert — SERVER-SET, and the cursor: pass a page's last id back as `since`. It rises with arrival order but is not contiguous, because one sequence is shared by every org in the store and a caller reads only its own rows.
	Id *int64 `json:"id,omitempty"`
	// ReplyTo is the transport's reply target for this message: Slack's thread_ts, or the Telegram message id it arrived as. Send it back as the body's `replyTo` to answer in the SAME thread. Empty means the transport reported none — a top-level Slack message, and every Discord and Teams message, since neither carries one — and a reply then lands at the top level of the room.
	ReplyTo *string `json:"replyTo,omitempty"`
	// RoomID is the conversation on the ORIGINATING transport, and the value to send back as `room.id`: a Discord channel snowflake, a Slack conversation id (D… IM, C… public channel, G… private or mpim), a Teams conversation id (19:…@thread.… for a channel or group chat, a:… for a personal chat), or a Telegram chat id in decimal (negative for a group, positive for a DM). It is stable for the life of the room, so every message from one conversation carries the same value.
	RoomId *string `json:"roomId,omitempty"`
	// RoomKind is how ingest classified the room: \"dm\", \"group\" or \"thread\". It decides which policy gated the message — dmPolicy for \"dm\", groupPolicy for BOTH \"group\" and \"thread\". Only Slack ever reports \"thread\"; Telegram's reply-to id becomes ReplyTo instead, and Discord's ingress is guild-scoped so its rooms are always \"group\".
	RoomKind *string `json:"roomKind,omitempty"`
	// Sender is the TRANSPORT-NATIVE user id of whoever wrote the message — a Discord member.user.id, a Slack U… user id, a Teams aadObjectId (falling back to from.id), a Telegram from.id in decimal. Stable per person per transport, and the identity the gate keys on: an allow entry, an access-group member and a pairing approval all name exactly this value.
	Sender *string `json:"sender,omitempty"`
	// SenderUser is the HANZO account subject that chat identity is linked to, resolved at ingest through the org's user link. Best-effort and omitted when absent: a person who never linked their chat account — or a link store that could not be read — leaves it empty and is never blocked for it.
	SenderUser *string `json:"senderUser,omitempty"`
	// Text is the body as the transport delivered it, with the bot mention already stripped by the ingress adapter (on Discord it is the /hanzo prompt argument, since that ingress is slash commands only), truncated to 8 KiB on store. Inbound attachments are not stored — this is the whole of what was said.
	Text                 *string `json:"text,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChannelInboxView ChannelInboxView

// NewChannelInboxView instantiates a new ChannelInboxView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelInboxView() *ChannelInboxView {
	this := ChannelInboxView{}
	return &this
}

// NewChannelInboxViewWithDefaults instantiates a new ChannelInboxView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelInboxViewWithDefaults() *ChannelInboxView {
	this := ChannelInboxView{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ChannelInboxView) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ChannelInboxView) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *ChannelInboxView) SetAccount(v string) {
	o.Account = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ChannelInboxView) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ChannelInboxView) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *ChannelInboxView) SetChannel(v string) {
	o.Channel = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ChannelInboxView) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ChannelInboxView) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *ChannelInboxView) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChannelInboxView) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChannelInboxView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ChannelInboxView) SetId(v int64) {
	o.Id = &v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *ChannelInboxView) GetReplyTo() string {
	if o == nil || IsNil(o.ReplyTo) {
		var ret string
		return ret
	}
	return *o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetReplyToOk() (*string, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *ChannelInboxView) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given string and assigns it to the ReplyTo field.
func (o *ChannelInboxView) SetReplyTo(v string) {
	o.ReplyTo = &v
}

// GetRoomId returns the RoomId field value if set, zero value otherwise.
func (o *ChannelInboxView) GetRoomId() string {
	if o == nil || IsNil(o.RoomId) {
		var ret string
		return ret
	}
	return *o.RoomId
}

// GetRoomIdOk returns a tuple with the RoomId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetRoomIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoomId) {
		return nil, false
	}
	return o.RoomId, true
}

// HasRoomId returns a boolean if a field has been set.
func (o *ChannelInboxView) HasRoomId() bool {
	if o != nil && !IsNil(o.RoomId) {
		return true
	}

	return false
}

// SetRoomId gets a reference to the given string and assigns it to the RoomId field.
func (o *ChannelInboxView) SetRoomId(v string) {
	o.RoomId = &v
}

// GetRoomKind returns the RoomKind field value if set, zero value otherwise.
func (o *ChannelInboxView) GetRoomKind() string {
	if o == nil || IsNil(o.RoomKind) {
		var ret string
		return ret
	}
	return *o.RoomKind
}

// GetRoomKindOk returns a tuple with the RoomKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetRoomKindOk() (*string, bool) {
	if o == nil || IsNil(o.RoomKind) {
		return nil, false
	}
	return o.RoomKind, true
}

// HasRoomKind returns a boolean if a field has been set.
func (o *ChannelInboxView) HasRoomKind() bool {
	if o != nil && !IsNil(o.RoomKind) {
		return true
	}

	return false
}

// SetRoomKind gets a reference to the given string and assigns it to the RoomKind field.
func (o *ChannelInboxView) SetRoomKind(v string) {
	o.RoomKind = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *ChannelInboxView) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *ChannelInboxView) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *ChannelInboxView) SetSender(v string) {
	o.Sender = &v
}

// GetSenderUser returns the SenderUser field value if set, zero value otherwise.
func (o *ChannelInboxView) GetSenderUser() string {
	if o == nil || IsNil(o.SenderUser) {
		var ret string
		return ret
	}
	return *o.SenderUser
}

// GetSenderUserOk returns a tuple with the SenderUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetSenderUserOk() (*string, bool) {
	if o == nil || IsNil(o.SenderUser) {
		return nil, false
	}
	return o.SenderUser, true
}

// HasSenderUser returns a boolean if a field has been set.
func (o *ChannelInboxView) HasSenderUser() bool {
	if o != nil && !IsNil(o.SenderUser) {
		return true
	}

	return false
}

// SetSenderUser gets a reference to the given string and assigns it to the SenderUser field.
func (o *ChannelInboxView) SetSenderUser(v string) {
	o.SenderUser = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ChannelInboxView) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelInboxView) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ChannelInboxView) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ChannelInboxView) SetText(v string) {
	o.Text = &v
}

func (o ChannelInboxView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelInboxView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["replyTo"] = o.ReplyTo
	}
	if !IsNil(o.RoomId) {
		toSerialize["roomId"] = o.RoomId
	}
	if !IsNil(o.RoomKind) {
		toSerialize["roomKind"] = o.RoomKind
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if !IsNil(o.SenderUser) {
		toSerialize["senderUser"] = o.SenderUser
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelInboxView) UnmarshalJSON(data []byte) (err error) {
	varChannelInboxView := _ChannelInboxView{}

	err = json.Unmarshal(data, &varChannelInboxView)

	if err != nil {
		return err
	}

	*o = ChannelInboxView(varChannelInboxView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "id")
		delete(additionalProperties, "replyTo")
		delete(additionalProperties, "roomId")
		delete(additionalProperties, "roomKind")
		delete(additionalProperties, "sender")
		delete(additionalProperties, "senderUser")
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelInboxView struct {
	value *ChannelInboxView
	isSet bool
}

func (v NullableChannelInboxView) Get() *ChannelInboxView {
	return v.value
}

func (v *NullableChannelInboxView) Set(val *ChannelInboxView) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelInboxView) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelInboxView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelInboxView(val *ChannelInboxView) *NullableChannelInboxView {
	return &NullableChannelInboxView{value: val, isSet: true}
}

func (v NullableChannelInboxView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelInboxView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
