/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the CampaignChannelSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignChannelSpec{}

// CampaignChannelSpec struct for CampaignChannelSpec
type CampaignChannelSpec struct {
	// Account is the provider account this channel runs under: an ad-account, a page or a mailing-list id. An executor may replace it at launch with the account it actually used.
	Account *string `json:"account,omitempty"`
	// Detail is the last outcome in one secret-free line — the failure reason, or what the executor reported. Absent when there is nothing to explain.
	Detail *string `json:"detail,omitempty"`
	// ExternalID is the provider-side id of the running execution, recorded by the orchestrator at launch and handed back verbatim to read spend or to pause. Server-owned and absent until this channel has launched; anything a caller sends for it is dropped.
	ExternalId *string `json:"externalId,omitempty"`
	// Kind is the channel and the identity a campaign holds at most one of: paid, organic or email. It picks the executor the launch fans out to.
	Kind *string `json:"kind,omitempty"`
	// Platform is the provider within the kind — meta, google, x, instagram, or the email provider.
	Platform *string `json:"platform,omitempty"`
	// Status is this channel's own launch outcome, not the campaign's: pending (added, never launched), live, paused, failed (Detail says why) or unavailable (no executor wired on this deployment). Server-owned — a caller can never assert it.
	Status               *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CampaignChannelSpec CampaignChannelSpec

// NewCampaignChannelSpec instantiates a new CampaignChannelSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignChannelSpec() *CampaignChannelSpec {
	this := CampaignChannelSpec{}
	return &this
}

// NewCampaignChannelSpecWithDefaults instantiates a new CampaignChannelSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignChannelSpecWithDefaults() *CampaignChannelSpec {
	this := CampaignChannelSpec{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *CampaignChannelSpec) SetAccount(v string) {
	o.Account = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *CampaignChannelSpec) SetDetail(v string) {
	o.Detail = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CampaignChannelSpec) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CampaignChannelSpec) SetKind(v string) {
	o.Kind = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *CampaignChannelSpec) SetPlatform(v string) {
	o.Platform = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CampaignChannelSpec) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignChannelSpec) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CampaignChannelSpec) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CampaignChannelSpec) SetStatus(v string) {
	o.Status = &v
}

func (o CampaignChannelSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignChannelSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CampaignChannelSpec) UnmarshalJSON(data []byte) (err error) {
	varCampaignChannelSpec := _CampaignChannelSpec{}

	err = json.Unmarshal(data, &varCampaignChannelSpec)

	if err != nil {
		return err
	}

	*o = CampaignChannelSpec(varCampaignChannelSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "detail")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaignChannelSpec struct {
	value *CampaignChannelSpec
	isSet bool
}

func (v NullableCampaignChannelSpec) Get() *CampaignChannelSpec {
	return v.value
}

func (v *NullableCampaignChannelSpec) Set(val *CampaignChannelSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignChannelSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignChannelSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignChannelSpec(val *CampaignChannelSpec) *NullableCampaignChannelSpec {
	return &NullableCampaignChannelSpec{value: val, isSet: true}
}

func (v NullableCampaignChannelSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignChannelSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
