/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TrustPolicyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustPolicyList{}

// TrustPolicyList struct for TrustPolicyList
type TrustPolicyList struct {
	// Policies is the organization's published policy documents, each as the centre holds it.
	Policies             []interface{} `json:"policies,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TrustPolicyList TrustPolicyList

// NewTrustPolicyList instantiates a new TrustPolicyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustPolicyList() *TrustPolicyList {
	this := TrustPolicyList{}
	return &this
}

// NewTrustPolicyListWithDefaults instantiates a new TrustPolicyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustPolicyListWithDefaults() *TrustPolicyList {
	this := TrustPolicyList{}
	return &this
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *TrustPolicyList) GetPolicies() []interface{} {
	if o == nil || IsNil(o.Policies) {
		var ret []interface{}
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustPolicyList) GetPoliciesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *TrustPolicyList) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []interface{} and assigns it to the Policies field.
func (o *TrustPolicyList) SetPolicies(v []interface{}) {
	o.Policies = v
}

func (o TrustPolicyList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustPolicyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TrustPolicyList) UnmarshalJSON(data []byte) (err error) {
	varTrustPolicyList := _TrustPolicyList{}

	err = json.Unmarshal(data, &varTrustPolicyList)

	if err != nil {
		return err
	}

	*o = TrustPolicyList(varTrustPolicyList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "policies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTrustPolicyList struct {
	value *TrustPolicyList
	isSet bool
}

func (v NullableTrustPolicyList) Get() *TrustPolicyList {
	return v.value
}

func (v *NullableTrustPolicyList) Set(val *TrustPolicyList) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustPolicyList) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustPolicyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustPolicyList(val *TrustPolicyList) *NullableTrustPolicyList {
	return &NullableTrustPolicyList{value: val, isSet: true}
}

func (v NullableTrustPolicyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustPolicyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
