/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the HelpHelpArticleList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelpHelpArticleList{}

// HelpHelpArticleList struct for HelpHelpArticleList
type HelpHelpArticleList struct {
	// Data is the matching Published, public articles, newest write order last — the store's order, not a ranking. Empty when the center has none.
	Data                 []HelpHelpArticleCard `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HelpHelpArticleList HelpHelpArticleList

// NewHelpHelpArticleList instantiates a new HelpHelpArticleList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelpHelpArticleList() *HelpHelpArticleList {
	this := HelpHelpArticleList{}
	return &this
}

// NewHelpHelpArticleListWithDefaults instantiates a new HelpHelpArticleList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelpHelpArticleListWithDefaults() *HelpHelpArticleList {
	this := HelpHelpArticleList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *HelpHelpArticleList) GetData() []HelpHelpArticleCard {
	if o == nil || IsNil(o.Data) {
		var ret []HelpHelpArticleCard
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelpHelpArticleList) GetDataOk() ([]HelpHelpArticleCard, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *HelpHelpArticleList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []HelpHelpArticleCard and assigns it to the Data field.
func (o *HelpHelpArticleList) SetData(v []HelpHelpArticleCard) {
	o.Data = v
}

func (o HelpHelpArticleList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelpHelpArticleList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelpHelpArticleList) UnmarshalJSON(data []byte) (err error) {
	varHelpHelpArticleList := _HelpHelpArticleList{}

	err = json.Unmarshal(data, &varHelpHelpArticleList)

	if err != nil {
		return err
	}

	*o = HelpHelpArticleList(varHelpHelpArticleList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelpHelpArticleList struct {
	value *HelpHelpArticleList
	isSet bool
}

func (v NullableHelpHelpArticleList) Get() *HelpHelpArticleList {
	return v.value
}

func (v *NullableHelpHelpArticleList) Set(val *HelpHelpArticleList) {
	v.value = val
	v.isSet = true
}

func (v NullableHelpHelpArticleList) IsSet() bool {
	return v.isSet
}

func (v *NullableHelpHelpArticleList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelpHelpArticleList(val *HelpHelpArticleList) *NullableHelpHelpArticleList {
	return &NullableHelpHelpArticleList{value: val, isSet: true}
}

func (v NullableHelpHelpArticleList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelpHelpArticleList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
