/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the MarketplaceDispute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceDispute{}

// MarketplaceDispute struct for MarketplaceDispute
type MarketplaceDispute struct {
	// At is when, unix seconds.
	At *int64 `json:"at,omitempty"`
	// By is the org that disputed.
	By *string `json:"by,omitempty"`
	// Contested is the clock's own dispute: the payment stopped clearing when the review window closed. A party's dispute never carries it, whatever the party is named.
	Contested *bool `json:"contested,omitempty"`
	// Reason is the disputing party's words.
	Reason               *string `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketplaceDispute MarketplaceDispute

// NewMarketplaceDispute instantiates a new MarketplaceDispute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceDispute() *MarketplaceDispute {
	this := MarketplaceDispute{}
	return &this
}

// NewMarketplaceDisputeWithDefaults instantiates a new MarketplaceDispute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceDisputeWithDefaults() *MarketplaceDispute {
	this := MarketplaceDispute{}
	return &this
}

// GetAt returns the At field value if set, zero value otherwise.
func (o *MarketplaceDispute) GetAt() int64 {
	if o == nil || IsNil(o.At) {
		var ret int64
		return ret
	}
	return *o.At
}

// GetAtOk returns a tuple with the At field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDispute) GetAtOk() (*int64, bool) {
	if o == nil || IsNil(o.At) {
		return nil, false
	}
	return o.At, true
}

// HasAt returns a boolean if a field has been set.
func (o *MarketplaceDispute) HasAt() bool {
	if o != nil && !IsNil(o.At) {
		return true
	}

	return false
}

// SetAt gets a reference to the given int64 and assigns it to the At field.
func (o *MarketplaceDispute) SetAt(v int64) {
	o.At = &v
}

// GetBy returns the By field value if set, zero value otherwise.
func (o *MarketplaceDispute) GetBy() string {
	if o == nil || IsNil(o.By) {
		var ret string
		return ret
	}
	return *o.By
}

// GetByOk returns a tuple with the By field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDispute) GetByOk() (*string, bool) {
	if o == nil || IsNil(o.By) {
		return nil, false
	}
	return o.By, true
}

// HasBy returns a boolean if a field has been set.
func (o *MarketplaceDispute) HasBy() bool {
	if o != nil && !IsNil(o.By) {
		return true
	}

	return false
}

// SetBy gets a reference to the given string and assigns it to the By field.
func (o *MarketplaceDispute) SetBy(v string) {
	o.By = &v
}

// GetContested returns the Contested field value if set, zero value otherwise.
func (o *MarketplaceDispute) GetContested() bool {
	if o == nil || IsNil(o.Contested) {
		var ret bool
		return ret
	}
	return *o.Contested
}

// GetContestedOk returns a tuple with the Contested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDispute) GetContestedOk() (*bool, bool) {
	if o == nil || IsNil(o.Contested) {
		return nil, false
	}
	return o.Contested, true
}

// HasContested returns a boolean if a field has been set.
func (o *MarketplaceDispute) HasContested() bool {
	if o != nil && !IsNil(o.Contested) {
		return true
	}

	return false
}

// SetContested gets a reference to the given bool and assigns it to the Contested field.
func (o *MarketplaceDispute) SetContested(v bool) {
	o.Contested = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *MarketplaceDispute) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceDispute) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *MarketplaceDispute) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *MarketplaceDispute) SetReason(v string) {
	o.Reason = &v
}

func (o MarketplaceDispute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceDispute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.At) {
		toSerialize["at"] = o.At
	}
	if !IsNil(o.By) {
		toSerialize["by"] = o.By
	}
	if !IsNil(o.Contested) {
		toSerialize["contested"] = o.Contested
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketplaceDispute) UnmarshalJSON(data []byte) (err error) {
	varMarketplaceDispute := _MarketplaceDispute{}

	err = json.Unmarshal(data, &varMarketplaceDispute)

	if err != nil {
		return err
	}

	*o = MarketplaceDispute(varMarketplaceDispute)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "at")
		delete(additionalProperties, "by")
		delete(additionalProperties, "contested")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketplaceDispute struct {
	value *MarketplaceDispute
	isSet bool
}

func (v NullableMarketplaceDispute) Get() *MarketplaceDispute {
	return v.value
}

func (v *NullableMarketplaceDispute) Set(val *MarketplaceDispute) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceDispute) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceDispute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceDispute(val *MarketplaceDispute) *NullableMarketplaceDispute {
	return &NullableMarketplaceDispute{value: val, isSet: true}
}

func (v NullableMarketplaceDispute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceDispute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
