/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the SandboxWriteIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxWriteIn{}

// SandboxWriteIn struct for SandboxWriteIn
type SandboxWriteIn struct {
	// Data is the file's bytes, and replaces whatever was there.
	Data *string `json:"data,omitempty"`
	// ID is the sandbox to write into, from an earlier lease.
	Id *string `json:"id,omitempty"`
	// Path is confined the same way PathIn.Path is. Missing parent directories are created.
	Path                 *string `json:"path,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SandboxWriteIn SandboxWriteIn

// NewSandboxWriteIn instantiates a new SandboxWriteIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxWriteIn() *SandboxWriteIn {
	this := SandboxWriteIn{}
	return &this
}

// NewSandboxWriteInWithDefaults instantiates a new SandboxWriteIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxWriteInWithDefaults() *SandboxWriteIn {
	this := SandboxWriteIn{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SandboxWriteIn) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxWriteIn) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SandboxWriteIn) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *SandboxWriteIn) SetData(v string) {
	o.Data = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SandboxWriteIn) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxWriteIn) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SandboxWriteIn) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SandboxWriteIn) SetId(v string) {
	o.Id = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *SandboxWriteIn) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxWriteIn) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *SandboxWriteIn) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *SandboxWriteIn) SetPath(v string) {
	o.Path = &v
}

func (o SandboxWriteIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxWriteIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SandboxWriteIn) UnmarshalJSON(data []byte) (err error) {
	varSandboxWriteIn := _SandboxWriteIn{}

	err = json.Unmarshal(data, &varSandboxWriteIn)

	if err != nil {
		return err
	}

	*o = SandboxWriteIn(varSandboxWriteIn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "id")
		delete(additionalProperties, "path")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSandboxWriteIn struct {
	value *SandboxWriteIn
	isSet bool
}

func (v NullableSandboxWriteIn) Get() *SandboxWriteIn {
	return v.value
}

func (v *NullableSandboxWriteIn) Set(val *SandboxWriteIn) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxWriteIn) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxWriteIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxWriteIn(val *SandboxWriteIn) *NullableSandboxWriteIn {
	return &NullableSandboxWriteIn{value: val, isSet: true}
}

func (v NullableSandboxWriteIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxWriteIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
