/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the IamAuditlogsDeleteOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IamAuditlogsDeleteOutput{}

// IamAuditlogsDeleteOutput struct for IamAuditlogsDeleteOutput
type IamAuditlogsDeleteOutput struct {
	Deleted              *bool `json:"deleted,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IamAuditlogsDeleteOutput IamAuditlogsDeleteOutput

// NewIamAuditlogsDeleteOutput instantiates a new IamAuditlogsDeleteOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIamAuditlogsDeleteOutput() *IamAuditlogsDeleteOutput {
	this := IamAuditlogsDeleteOutput{}
	return &this
}

// NewIamAuditlogsDeleteOutputWithDefaults instantiates a new IamAuditlogsDeleteOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIamAuditlogsDeleteOutputWithDefaults() *IamAuditlogsDeleteOutput {
	this := IamAuditlogsDeleteOutput{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *IamAuditlogsDeleteOutput) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamAuditlogsDeleteOutput) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *IamAuditlogsDeleteOutput) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *IamAuditlogsDeleteOutput) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o IamAuditlogsDeleteOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IamAuditlogsDeleteOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IamAuditlogsDeleteOutput) UnmarshalJSON(data []byte) (err error) {
	varIamAuditlogsDeleteOutput := _IamAuditlogsDeleteOutput{}

	err = json.Unmarshal(data, &varIamAuditlogsDeleteOutput)

	if err != nil {
		return err
	}

	*o = IamAuditlogsDeleteOutput(varIamAuditlogsDeleteOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deleted")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIamAuditlogsDeleteOutput struct {
	value *IamAuditlogsDeleteOutput
	isSet bool
}

func (v NullableIamAuditlogsDeleteOutput) Get() *IamAuditlogsDeleteOutput {
	return v.value
}

func (v *NullableIamAuditlogsDeleteOutput) Set(val *IamAuditlogsDeleteOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableIamAuditlogsDeleteOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableIamAuditlogsDeleteOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIamAuditlogsDeleteOutput(val *IamAuditlogsDeleteOutput) *NullableIamAuditlogsDeleteOutput {
	return &NullableIamAuditlogsDeleteOutput{value: val, isSet: true}
}

func (v NullableIamAuditlogsDeleteOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIamAuditlogsDeleteOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
