/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the LabelRiskLabelVocabulary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelRiskLabelVocabulary{}

// LabelRiskLabelVocabulary struct for LabelRiskLabelVocabulary
type LabelRiskLabelVocabulary struct {
	// Dispositions is the closed set a write's `disposition` must be drawn from, published in full so a caller can validate a batch before filing it instead of discovering a refusal per member: \"productive\", \"unproductive\", and \"\" — the EMPTY STRING is a member and means an explicit unjudged, so a client that filters empties out of this list drops a third of the vocabulary and can never file \"we looked and could not say\". They are the AML engine's own spelling, verbatim, which is what lets a replay there report against these values.
	Dispositions []string `json:"dispositions,omitempty"`
	// Kinds, Dispositions and Sources are the closed vocabularies. A value outside them is refused at the endpoint.
	Kinds []string `json:"kinds,omitempty"`
	// Precedence is the sources in the order that resolves a conflict, strongest first. It is DERIVED from the same declaration the resolver reads, so the published order is the enforced order and cannot drift from it.
	Precedence []string `json:"precedence,omitempty"`
	// Retention is the platform floor in days: no tenant may dispose of a label younger than this, because a label can be the input to an adverse action.
	Retention *int64 `json:"retention,omitempty"`
	// Rule states the tie-breaks below rank, in order, so a caller reading a contested resolution can reproduce it.
	Rule                 []string `json:"rule,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelRiskLabelVocabulary LabelRiskLabelVocabulary

// NewLabelRiskLabelVocabulary instantiates a new LabelRiskLabelVocabulary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelRiskLabelVocabulary() *LabelRiskLabelVocabulary {
	this := LabelRiskLabelVocabulary{}
	return &this
}

// NewLabelRiskLabelVocabularyWithDefaults instantiates a new LabelRiskLabelVocabulary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelRiskLabelVocabularyWithDefaults() *LabelRiskLabelVocabulary {
	this := LabelRiskLabelVocabulary{}
	return &this
}

// GetDispositions returns the Dispositions field value if set, zero value otherwise.
func (o *LabelRiskLabelVocabulary) GetDispositions() []string {
	if o == nil || IsNil(o.Dispositions) {
		var ret []string
		return ret
	}
	return o.Dispositions
}

// GetDispositionsOk returns a tuple with the Dispositions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelRiskLabelVocabulary) GetDispositionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Dispositions) {
		return nil, false
	}
	return o.Dispositions, true
}

// HasDispositions returns a boolean if a field has been set.
func (o *LabelRiskLabelVocabulary) HasDispositions() bool {
	if o != nil && !IsNil(o.Dispositions) {
		return true
	}

	return false
}

// SetDispositions gets a reference to the given []string and assigns it to the Dispositions field.
func (o *LabelRiskLabelVocabulary) SetDispositions(v []string) {
	o.Dispositions = v
}

// GetKinds returns the Kinds field value if set, zero value otherwise.
func (o *LabelRiskLabelVocabulary) GetKinds() []string {
	if o == nil || IsNil(o.Kinds) {
		var ret []string
		return ret
	}
	return o.Kinds
}

// GetKindsOk returns a tuple with the Kinds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelRiskLabelVocabulary) GetKindsOk() ([]string, bool) {
	if o == nil || IsNil(o.Kinds) {
		return nil, false
	}
	return o.Kinds, true
}

// HasKinds returns a boolean if a field has been set.
func (o *LabelRiskLabelVocabulary) HasKinds() bool {
	if o != nil && !IsNil(o.Kinds) {
		return true
	}

	return false
}

// SetKinds gets a reference to the given []string and assigns it to the Kinds field.
func (o *LabelRiskLabelVocabulary) SetKinds(v []string) {
	o.Kinds = v
}

// GetPrecedence returns the Precedence field value if set, zero value otherwise.
func (o *LabelRiskLabelVocabulary) GetPrecedence() []string {
	if o == nil || IsNil(o.Precedence) {
		var ret []string
		return ret
	}
	return o.Precedence
}

// GetPrecedenceOk returns a tuple with the Precedence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelRiskLabelVocabulary) GetPrecedenceOk() ([]string, bool) {
	if o == nil || IsNil(o.Precedence) {
		return nil, false
	}
	return o.Precedence, true
}

// HasPrecedence returns a boolean if a field has been set.
func (o *LabelRiskLabelVocabulary) HasPrecedence() bool {
	if o != nil && !IsNil(o.Precedence) {
		return true
	}

	return false
}

// SetPrecedence gets a reference to the given []string and assigns it to the Precedence field.
func (o *LabelRiskLabelVocabulary) SetPrecedence(v []string) {
	o.Precedence = v
}

// GetRetention returns the Retention field value if set, zero value otherwise.
func (o *LabelRiskLabelVocabulary) GetRetention() int64 {
	if o == nil || IsNil(o.Retention) {
		var ret int64
		return ret
	}
	return *o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelRiskLabelVocabulary) GetRetentionOk() (*int64, bool) {
	if o == nil || IsNil(o.Retention) {
		return nil, false
	}
	return o.Retention, true
}

// HasRetention returns a boolean if a field has been set.
func (o *LabelRiskLabelVocabulary) HasRetention() bool {
	if o != nil && !IsNil(o.Retention) {
		return true
	}

	return false
}

// SetRetention gets a reference to the given int64 and assigns it to the Retention field.
func (o *LabelRiskLabelVocabulary) SetRetention(v int64) {
	o.Retention = &v
}

// GetRule returns the Rule field value if set, zero value otherwise.
func (o *LabelRiskLabelVocabulary) GetRule() []string {
	if o == nil || IsNil(o.Rule) {
		var ret []string
		return ret
	}
	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelRiskLabelVocabulary) GetRuleOk() ([]string, bool) {
	if o == nil || IsNil(o.Rule) {
		return nil, false
	}
	return o.Rule, true
}

// HasRule returns a boolean if a field has been set.
func (o *LabelRiskLabelVocabulary) HasRule() bool {
	if o != nil && !IsNil(o.Rule) {
		return true
	}

	return false
}

// SetRule gets a reference to the given []string and assigns it to the Rule field.
func (o *LabelRiskLabelVocabulary) SetRule(v []string) {
	o.Rule = v
}

func (o LabelRiskLabelVocabulary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelRiskLabelVocabulary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dispositions) {
		toSerialize["dispositions"] = o.Dispositions
	}
	if !IsNil(o.Kinds) {
		toSerialize["kinds"] = o.Kinds
	}
	if !IsNil(o.Precedence) {
		toSerialize["precedence"] = o.Precedence
	}
	if !IsNil(o.Retention) {
		toSerialize["retention"] = o.Retention
	}
	if !IsNil(o.Rule) {
		toSerialize["rule"] = o.Rule
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelRiskLabelVocabulary) UnmarshalJSON(data []byte) (err error) {
	varLabelRiskLabelVocabulary := _LabelRiskLabelVocabulary{}

	err = json.Unmarshal(data, &varLabelRiskLabelVocabulary)

	if err != nil {
		return err
	}

	*o = LabelRiskLabelVocabulary(varLabelRiskLabelVocabulary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dispositions")
		delete(additionalProperties, "kinds")
		delete(additionalProperties, "precedence")
		delete(additionalProperties, "retention")
		delete(additionalProperties, "rule")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLabelRiskLabelVocabulary struct {
	value *LabelRiskLabelVocabulary
	isSet bool
}

func (v NullableLabelRiskLabelVocabulary) Get() *LabelRiskLabelVocabulary {
	return v.value
}

func (v *NullableLabelRiskLabelVocabulary) Set(val *LabelRiskLabelVocabulary) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelRiskLabelVocabulary) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelRiskLabelVocabulary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelRiskLabelVocabulary(val *LabelRiskLabelVocabulary) *NullableLabelRiskLabelVocabulary {
	return &NullableLabelRiskLabelVocabulary{value: val, isSet: true}
}

func (v NullableLabelRiskLabelVocabulary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelRiskLabelVocabulary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
