/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the MarketplaceMarketCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceMarketCatalog{}

// MarketplaceMarketCatalog struct for MarketplaceMarketCatalog
type MarketplaceMarketCatalog struct {
	// Items is every capability the caller can see in their own (org, project), each carrying any public listing's shop metadata and whether it is installed.
	Items                []MarketplaceMarketItem `json:"items,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketplaceMarketCatalog MarketplaceMarketCatalog

// NewMarketplaceMarketCatalog instantiates a new MarketplaceMarketCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceMarketCatalog() *MarketplaceMarketCatalog {
	this := MarketplaceMarketCatalog{}
	return &this
}

// NewMarketplaceMarketCatalogWithDefaults instantiates a new MarketplaceMarketCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceMarketCatalogWithDefaults() *MarketplaceMarketCatalog {
	this := MarketplaceMarketCatalog{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *MarketplaceMarketCatalog) GetItems() []MarketplaceMarketItem {
	if o == nil || IsNil(o.Items) {
		var ret []MarketplaceMarketItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceMarketCatalog) GetItemsOk() ([]MarketplaceMarketItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *MarketplaceMarketCatalog) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []MarketplaceMarketItem and assigns it to the Items field.
func (o *MarketplaceMarketCatalog) SetItems(v []MarketplaceMarketItem) {
	o.Items = v
}

func (o MarketplaceMarketCatalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceMarketCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketplaceMarketCatalog) UnmarshalJSON(data []byte) (err error) {
	varMarketplaceMarketCatalog := _MarketplaceMarketCatalog{}

	err = json.Unmarshal(data, &varMarketplaceMarketCatalog)

	if err != nil {
		return err
	}

	*o = MarketplaceMarketCatalog(varMarketplaceMarketCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketplaceMarketCatalog struct {
	value *MarketplaceMarketCatalog
	isSet bool
}

func (v NullableMarketplaceMarketCatalog) Get() *MarketplaceMarketCatalog {
	return v.value
}

func (v *NullableMarketplaceMarketCatalog) Set(val *MarketplaceMarketCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceMarketCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceMarketCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceMarketCatalog(val *MarketplaceMarketCatalog) *NullableMarketplaceMarketCatalog {
	return &NullableMarketplaceMarketCatalog{value: val, isSet: true}
}

func (v NullableMarketplaceMarketCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceMarketCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
