/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the EsignEsignRejectIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsignEsignRejectIn{}

// EsignEsignRejectIn struct for EsignEsignRejectIn
type EsignEsignRejectIn struct {
	Reason               interface{} `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EsignEsignRejectIn EsignEsignRejectIn

// NewEsignEsignRejectIn instantiates a new EsignEsignRejectIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsignEsignRejectIn() *EsignEsignRejectIn {
	this := EsignEsignRejectIn{}
	return &this
}

// NewEsignEsignRejectInWithDefaults instantiates a new EsignEsignRejectIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsignEsignRejectInWithDefaults() *EsignEsignRejectIn {
	this := EsignEsignRejectIn{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EsignEsignRejectIn) GetReason() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EsignEsignRejectIn) GetReasonOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return &o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *EsignEsignRejectIn) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given interface{} and assigns it to the Reason field.
func (o *EsignEsignRejectIn) SetReason(v interface{}) {
	o.Reason = v
}

func (o EsignEsignRejectIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsignEsignRejectIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EsignEsignRejectIn) UnmarshalJSON(data []byte) (err error) {
	varEsignEsignRejectIn := _EsignEsignRejectIn{}

	err = json.Unmarshal(data, &varEsignEsignRejectIn)

	if err != nil {
		return err
	}

	*o = EsignEsignRejectIn(varEsignEsignRejectIn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEsignEsignRejectIn struct {
	value *EsignEsignRejectIn
	isSet bool
}

func (v NullableEsignEsignRejectIn) Get() *EsignEsignRejectIn {
	return v.value
}

func (v *NullableEsignEsignRejectIn) Set(val *EsignEsignRejectIn) {
	v.value = val
	v.isSet = true
}

func (v NullableEsignEsignRejectIn) IsSet() bool {
	return v.isSet
}

func (v *NullableEsignEsignRejectIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsignEsignRejectIn(val *EsignEsignRejectIn) *NullableEsignEsignRejectIn {
	return &NullableEsignEsignRejectIn{value: val, isSet: true}
}

func (v NullableEsignEsignRejectIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsignEsignRejectIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
