/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the TeamTeamInboxAt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamTeamInboxAt{}

// TeamTeamInboxAt struct for TeamTeamInboxAt
type TeamTeamInboxAt struct {
	// ID is the notification, from the path.
	Id *string `json:"id,omitempty"`
	// Space is the space uuid it was filed in. Body-only.
	Space                *string `json:"space,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TeamTeamInboxAt TeamTeamInboxAt

// NewTeamTeamInboxAt instantiates a new TeamTeamInboxAt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamTeamInboxAt() *TeamTeamInboxAt {
	this := TeamTeamInboxAt{}
	return &this
}

// NewTeamTeamInboxAtWithDefaults instantiates a new TeamTeamInboxAt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamTeamInboxAtWithDefaults() *TeamTeamInboxAt {
	this := TeamTeamInboxAt{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TeamTeamInboxAt) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamInboxAt) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TeamTeamInboxAt) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TeamTeamInboxAt) SetId(v string) {
	o.Id = &v
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *TeamTeamInboxAt) GetSpace() string {
	if o == nil || IsNil(o.Space) {
		var ret string
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamTeamInboxAt) GetSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *TeamTeamInboxAt) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given string and assigns it to the Space field.
func (o *TeamTeamInboxAt) SetSpace(v string) {
	o.Space = &v
}

func (o TeamTeamInboxAt) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamTeamInboxAt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TeamTeamInboxAt) UnmarshalJSON(data []byte) (err error) {
	varTeamTeamInboxAt := _TeamTeamInboxAt{}

	err = json.Unmarshal(data, &varTeamTeamInboxAt)

	if err != nil {
		return err
	}

	*o = TeamTeamInboxAt(varTeamTeamInboxAt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "space")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTeamTeamInboxAt struct {
	value *TeamTeamInboxAt
	isSet bool
}

func (v NullableTeamTeamInboxAt) Get() *TeamTeamInboxAt {
	return v.value
}

func (v *NullableTeamTeamInboxAt) Set(val *TeamTeamInboxAt) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamTeamInboxAt) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamTeamInboxAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamTeamInboxAt(val *TeamTeamInboxAt) *NullableTeamTeamInboxAt {
	return &NullableTeamTeamInboxAt{value: val, isSet: true}
}

func (v NullableTeamTeamInboxAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamTeamInboxAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
