/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the GitKeyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitKeyList{}

// GitKeyList struct for GitKeyList
type GitKeyList struct {
	// Data holds the org's keys.
	Data                 []GitKeyView `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GitKeyList GitKeyList

// NewGitKeyList instantiates a new GitKeyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitKeyList() *GitKeyList {
	this := GitKeyList{}
	return &this
}

// NewGitKeyListWithDefaults instantiates a new GitKeyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitKeyListWithDefaults() *GitKeyList {
	this := GitKeyList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GitKeyList) GetData() []GitKeyView {
	if o == nil || IsNil(o.Data) {
		var ret []GitKeyView
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitKeyList) GetDataOk() ([]GitKeyView, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GitKeyList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GitKeyView and assigns it to the Data field.
func (o *GitKeyList) SetData(v []GitKeyView) {
	o.Data = v
}

func (o GitKeyList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitKeyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GitKeyList) UnmarshalJSON(data []byte) (err error) {
	varGitKeyList := _GitKeyList{}

	err = json.Unmarshal(data, &varGitKeyList)

	if err != nil {
		return err
	}

	*o = GitKeyList(varGitKeyList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGitKeyList struct {
	value *GitKeyList
	isSet bool
}

func (v NullableGitKeyList) Get() *GitKeyList {
	return v.value
}

func (v *NullableGitKeyList) Set(val *GitKeyList) {
	v.value = val
	v.isSet = true
}

func (v NullableGitKeyList) IsSet() bool {
	return v.isSet
}

func (v *NullableGitKeyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitKeyList(val *GitKeyList) *NullableGitKeyList {
	return &NullableGitKeyList{value: val, isSet: true}
}

func (v NullableGitKeyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitKeyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
