/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the MarketingRedeemInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketingRedeemInput{}

// MarketingRedeemInput struct for MarketingRedeemInput
type MarketingRedeemInput struct {
	// Code is the promo code from the path.
	Code *string `json:"code,omitempty"`
	// Instrument identifies the payment method. It is the anti-farming key: one redemption per instrument, fleet-wide, and it is REQUIRED — an absent instrument is refused, never waved through.
	Instrument           *string `json:"instrument,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketingRedeemInput MarketingRedeemInput

// NewMarketingRedeemInput instantiates a new MarketingRedeemInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketingRedeemInput() *MarketingRedeemInput {
	this := MarketingRedeemInput{}
	return &this
}

// NewMarketingRedeemInputWithDefaults instantiates a new MarketingRedeemInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketingRedeemInputWithDefaults() *MarketingRedeemInput {
	this := MarketingRedeemInput{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *MarketingRedeemInput) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketingRedeemInput) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *MarketingRedeemInput) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *MarketingRedeemInput) SetCode(v string) {
	o.Code = &v
}

// GetInstrument returns the Instrument field value if set, zero value otherwise.
func (o *MarketingRedeemInput) GetInstrument() string {
	if o == nil || IsNil(o.Instrument) {
		var ret string
		return ret
	}
	return *o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketingRedeemInput) GetInstrumentOk() (*string, bool) {
	if o == nil || IsNil(o.Instrument) {
		return nil, false
	}
	return o.Instrument, true
}

// HasInstrument returns a boolean if a field has been set.
func (o *MarketingRedeemInput) HasInstrument() bool {
	if o != nil && !IsNil(o.Instrument) {
		return true
	}

	return false
}

// SetInstrument gets a reference to the given string and assigns it to the Instrument field.
func (o *MarketingRedeemInput) SetInstrument(v string) {
	o.Instrument = &v
}

func (o MarketingRedeemInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketingRedeemInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Instrument) {
		toSerialize["instrument"] = o.Instrument
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketingRedeemInput) UnmarshalJSON(data []byte) (err error) {
	varMarketingRedeemInput := _MarketingRedeemInput{}

	err = json.Unmarshal(data, &varMarketingRedeemInput)

	if err != nil {
		return err
	}

	*o = MarketingRedeemInput(varMarketingRedeemInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "instrument")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketingRedeemInput struct {
	value *MarketingRedeemInput
	isSet bool
}

func (v NullableMarketingRedeemInput) Get() *MarketingRedeemInput {
	return v.value
}

func (v *NullableMarketingRedeemInput) Set(val *MarketingRedeemInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketingRedeemInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketingRedeemInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketingRedeemInput(val *MarketingRedeemInput) *NullableMarketingRedeemInput {
	return &NullableMarketingRedeemInput{value: val, isSet: true}
}

func (v NullableMarketingRedeemInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketingRedeemInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
