/*
Hanzo Cloud API

The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hanzoai

import (
	"encoding/json"
)

// checks if the BooksBalanceSheet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BooksBalanceSheet{}

// BooksBalanceSheet struct for BooksBalanceSheet
type BooksBalanceSheet struct {
	// AsOf is the posting time the statement is taken at, inclusive. A balance sheet is a snapshot, not a window, so there is no From. Absent means as of now.
	AsOf *string `json:"asOf,omitempty"`
	// Assets are what the org OWNS at that instant, one line per account that has a balance. Cash, receivables, funds captured but not yet settled.
	Assets []BooksBalanceLine `json:"assets,omitempty"`
	// Balanced is whether assets equal liabilities plus equity — the accounting equation, computed from the totals above rather than assumed. False means the ledger is broken, not that the statement is.
	Balanced *bool `json:"balanced,omitempty"`
	// Equity is what is left over for the owners. It carries a DERIVED retained earnings line holding cumulative income minus expense, because this ledger has no period close that sweeps the P&L into equity — without that line the equation would not close.
	Equity []BooksBalanceLine `json:"equity,omitempty"`
	// Liabilities are what the org OWES — including customers' unspent prepaid credit, which is their money until it is consumed and so is carried here rather than counted as revenue.
	Liabilities []BooksBalanceLine `json:"liabilities,omitempty"`
	// TotalAssets is the sum of the asset lines, in cents.
	TotalAssets *int64 `json:"totalAssets,omitempty"`
	// TotalEquity is the sum of the equity lines including retained earnings, in cents.
	TotalEquity *int64 `json:"totalEquity,omitempty"`
	// TotalLiabilities is the sum of the liability lines, in cents.
	TotalLiabilities     *int64 `json:"totalLiabilities,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BooksBalanceSheet BooksBalanceSheet

// NewBooksBalanceSheet instantiates a new BooksBalanceSheet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBooksBalanceSheet() *BooksBalanceSheet {
	this := BooksBalanceSheet{}
	return &this
}

// NewBooksBalanceSheetWithDefaults instantiates a new BooksBalanceSheet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBooksBalanceSheetWithDefaults() *BooksBalanceSheet {
	this := BooksBalanceSheet{}
	return &this
}

// GetAsOf returns the AsOf field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetAsOf() string {
	if o == nil || IsNil(o.AsOf) {
		var ret string
		return ret
	}
	return *o.AsOf
}

// GetAsOfOk returns a tuple with the AsOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetAsOfOk() (*string, bool) {
	if o == nil || IsNil(o.AsOf) {
		return nil, false
	}
	return o.AsOf, true
}

// HasAsOf returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasAsOf() bool {
	if o != nil && !IsNil(o.AsOf) {
		return true
	}

	return false
}

// SetAsOf gets a reference to the given string and assigns it to the AsOf field.
func (o *BooksBalanceSheet) SetAsOf(v string) {
	o.AsOf = &v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetAssets() []BooksBalanceLine {
	if o == nil || IsNil(o.Assets) {
		var ret []BooksBalanceLine
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetAssetsOk() ([]BooksBalanceLine, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []BooksBalanceLine and assigns it to the Assets field.
func (o *BooksBalanceSheet) SetAssets(v []BooksBalanceLine) {
	o.Assets = v
}

// GetBalanced returns the Balanced field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetBalanced() bool {
	if o == nil || IsNil(o.Balanced) {
		var ret bool
		return ret
	}
	return *o.Balanced
}

// GetBalancedOk returns a tuple with the Balanced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetBalancedOk() (*bool, bool) {
	if o == nil || IsNil(o.Balanced) {
		return nil, false
	}
	return o.Balanced, true
}

// HasBalanced returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasBalanced() bool {
	if o != nil && !IsNil(o.Balanced) {
		return true
	}

	return false
}

// SetBalanced gets a reference to the given bool and assigns it to the Balanced field.
func (o *BooksBalanceSheet) SetBalanced(v bool) {
	o.Balanced = &v
}

// GetEquity returns the Equity field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetEquity() []BooksBalanceLine {
	if o == nil || IsNil(o.Equity) {
		var ret []BooksBalanceLine
		return ret
	}
	return o.Equity
}

// GetEquityOk returns a tuple with the Equity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetEquityOk() ([]BooksBalanceLine, bool) {
	if o == nil || IsNil(o.Equity) {
		return nil, false
	}
	return o.Equity, true
}

// HasEquity returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasEquity() bool {
	if o != nil && !IsNil(o.Equity) {
		return true
	}

	return false
}

// SetEquity gets a reference to the given []BooksBalanceLine and assigns it to the Equity field.
func (o *BooksBalanceSheet) SetEquity(v []BooksBalanceLine) {
	o.Equity = v
}

// GetLiabilities returns the Liabilities field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetLiabilities() []BooksBalanceLine {
	if o == nil || IsNil(o.Liabilities) {
		var ret []BooksBalanceLine
		return ret
	}
	return o.Liabilities
}

// GetLiabilitiesOk returns a tuple with the Liabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetLiabilitiesOk() ([]BooksBalanceLine, bool) {
	if o == nil || IsNil(o.Liabilities) {
		return nil, false
	}
	return o.Liabilities, true
}

// HasLiabilities returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasLiabilities() bool {
	if o != nil && !IsNil(o.Liabilities) {
		return true
	}

	return false
}

// SetLiabilities gets a reference to the given []BooksBalanceLine and assigns it to the Liabilities field.
func (o *BooksBalanceSheet) SetLiabilities(v []BooksBalanceLine) {
	o.Liabilities = v
}

// GetTotalAssets returns the TotalAssets field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetTotalAssets() int64 {
	if o == nil || IsNil(o.TotalAssets) {
		var ret int64
		return ret
	}
	return *o.TotalAssets
}

// GetTotalAssetsOk returns a tuple with the TotalAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetTotalAssetsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalAssets) {
		return nil, false
	}
	return o.TotalAssets, true
}

// HasTotalAssets returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasTotalAssets() bool {
	if o != nil && !IsNil(o.TotalAssets) {
		return true
	}

	return false
}

// SetTotalAssets gets a reference to the given int64 and assigns it to the TotalAssets field.
func (o *BooksBalanceSheet) SetTotalAssets(v int64) {
	o.TotalAssets = &v
}

// GetTotalEquity returns the TotalEquity field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetTotalEquity() int64 {
	if o == nil || IsNil(o.TotalEquity) {
		var ret int64
		return ret
	}
	return *o.TotalEquity
}

// GetTotalEquityOk returns a tuple with the TotalEquity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetTotalEquityOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalEquity) {
		return nil, false
	}
	return o.TotalEquity, true
}

// HasTotalEquity returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasTotalEquity() bool {
	if o != nil && !IsNil(o.TotalEquity) {
		return true
	}

	return false
}

// SetTotalEquity gets a reference to the given int64 and assigns it to the TotalEquity field.
func (o *BooksBalanceSheet) SetTotalEquity(v int64) {
	o.TotalEquity = &v
}

// GetTotalLiabilities returns the TotalLiabilities field value if set, zero value otherwise.
func (o *BooksBalanceSheet) GetTotalLiabilities() int64 {
	if o == nil || IsNil(o.TotalLiabilities) {
		var ret int64
		return ret
	}
	return *o.TotalLiabilities
}

// GetTotalLiabilitiesOk returns a tuple with the TotalLiabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooksBalanceSheet) GetTotalLiabilitiesOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalLiabilities) {
		return nil, false
	}
	return o.TotalLiabilities, true
}

// HasTotalLiabilities returns a boolean if a field has been set.
func (o *BooksBalanceSheet) HasTotalLiabilities() bool {
	if o != nil && !IsNil(o.TotalLiabilities) {
		return true
	}

	return false
}

// SetTotalLiabilities gets a reference to the given int64 and assigns it to the TotalLiabilities field.
func (o *BooksBalanceSheet) SetTotalLiabilities(v int64) {
	o.TotalLiabilities = &v
}

func (o BooksBalanceSheet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BooksBalanceSheet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsOf) {
		toSerialize["asOf"] = o.AsOf
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Balanced) {
		toSerialize["balanced"] = o.Balanced
	}
	if !IsNil(o.Equity) {
		toSerialize["equity"] = o.Equity
	}
	if !IsNil(o.Liabilities) {
		toSerialize["liabilities"] = o.Liabilities
	}
	if !IsNil(o.TotalAssets) {
		toSerialize["totalAssets"] = o.TotalAssets
	}
	if !IsNil(o.TotalEquity) {
		toSerialize["totalEquity"] = o.TotalEquity
	}
	if !IsNil(o.TotalLiabilities) {
		toSerialize["totalLiabilities"] = o.TotalLiabilities
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BooksBalanceSheet) UnmarshalJSON(data []byte) (err error) {
	varBooksBalanceSheet := _BooksBalanceSheet{}

	err = json.Unmarshal(data, &varBooksBalanceSheet)

	if err != nil {
		return err
	}

	*o = BooksBalanceSheet(varBooksBalanceSheet)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asOf")
		delete(additionalProperties, "assets")
		delete(additionalProperties, "balanced")
		delete(additionalProperties, "equity")
		delete(additionalProperties, "liabilities")
		delete(additionalProperties, "totalAssets")
		delete(additionalProperties, "totalEquity")
		delete(additionalProperties, "totalLiabilities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBooksBalanceSheet struct {
	value *BooksBalanceSheet
	isSet bool
}

func (v NullableBooksBalanceSheet) Get() *BooksBalanceSheet {
	return v.value
}

func (v *NullableBooksBalanceSheet) Set(val *BooksBalanceSheet) {
	v.value = val
	v.isSet = true
}

func (v NullableBooksBalanceSheet) IsSet() bool {
	return v.isSet
}

func (v *NullableBooksBalanceSheet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBooksBalanceSheet(val *BooksBalanceSheet) *NullableBooksBalanceSheet {
	return &NullableBooksBalanceSheet{value: val, isSet: true}
}

func (v NullableBooksBalanceSheet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBooksBalanceSheet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
